//go:build linux && cgo && !agent

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package clustergen

import (
	"database/sql"
	"time"

	"github.com/canonical/lxd/lxd/db/types"
)

type AuthGroup struct {
	ID          int64
	Name        string
	Description string
}

type AuthGroupsIdentityProviderGroup struct {
	ID                      int64
	AuthGroupID             int64
	IdentityProviderGroupID int64
}

type AuthGroupsPermission struct {
	ID          int64
	AuthGroupID int64
	EntityType  types.EntityType
	EntityID    int64
	Entitlement string
}

type ClusterGroup struct {
	ID          int64
	Name        string
	Description string
}

type Config struct {
	ID    int64
	Key   string
	Value sql.NullString
}

type IdentitiesAuthGroup struct {
	ID          int64
	IdentityID  int64
	AuthGroupID int64
}

type IdentitiesProject struct {
	ID         int64
	IdentityID int64
	ProjectID  int64
}

type Identity struct {
	ID            int64
	AuthMethod    types.AuthMethod
	Type          types.IdentityType
	Identifier    string
	Name          string
	Metadata      string
	FirstSeenDate time.Time
	LastSeenDate  time.Time
	UpdatedDate   time.Time
}

type IdentityProviderGroup struct {
	ID   int64
	Name string
}

type Image struct {
	ID           int64
	Fingerprint  string
	Filename     string
	Size         int64
	Public       int64
	Architecture int64
	CreationDate sql.NullTime
	ExpiryDate   sql.NullTime
	UploadDate   time.Time
	Cached       int64
	LastUseDate  sql.NullTime
	AutoUpdate   int64
	ProjectID    int64
	Type         int64
}

type ImagesAlias struct {
	ID          int64
	Name        string
	ImageID     int64
	Description string
	ProjectID   int64
}

type ImagesNode struct {
	ID      int64
	ImageID int64
	NodeID  int64
}

type ImagesProfile struct {
	ImageID   int64
	ProfileID int64
}

type ImagesProperty struct {
	ID      int64
	ImageID int64
	Type    int64
	Key     string
	Value   sql.NullString
}

type ImagesSource struct {
	ID          int64
	ImageID     int64
	Server      string
	Protocol    int64
	Certificate string
	Alias       string
}

type Instance struct {
	ID           int64
	NodeID       int64
	Name         string
	Architecture int64
	Type         int64
	Ephemeral    int64
	CreationDate time.Time
	Stateful     int64
	LastUseDate  sql.NullTime
	Description  string
	ProjectID    int64
	ExpiryDate   sql.NullTime
}

type InstancesBackup struct {
	ID               int64
	InstanceID       int64
	Name             string
	CreationDate     sql.NullTime
	ExpiryDate       sql.NullTime
	ContainerOnly    int64
	OptimizedStorage int64
}

type InstancesConfig struct {
	ID         int64
	InstanceID int64
	Key        string
	Value      string
}

type InstancesDevice struct {
	ID         int64
	InstanceID int64
	Name       string
	Type       int64
}

type InstancesDevicesConfig struct {
	ID               int64
	InstanceDeviceID int64
	Key              string
	Value            string
}

type InstancesProfile struct {
	ID         int64
	InstanceID int64
	ProfileID  int64
	ApplyOrder int64
}

type InstancesSnapshot struct {
	ID           int64
	InstanceID   int64
	Name         string
	CreationDate time.Time
	Stateful     int64
	Description  string
	ExpiryDate   sql.NullTime
}

type InstancesSnapshotsConfig struct {
	ID                 int64
	InstanceSnapshotID int64
	Key                string
	Value              string
}

type InstancesSnapshotsDevice struct {
	ID                 int64
	InstanceSnapshotID int64
	Name               string
	Type               int64
}

type InstancesSnapshotsDevicesConfig struct {
	ID                       int64
	InstanceSnapshotDeviceID int64
	Key                      string
	Value                    string
}

type Network struct {
	ID          int64
	ProjectID   int64
	Name        string
	Description string
	State       int64
	Type        int64
}

type NetworksAcl struct {
	ID          int64
	ProjectID   int64
	Name        string
	Description string
	Ingress     string
	Egress      string
}

type NetworksAclsConfig struct {
	ID           int64
	NetworkAclID int64
	Key          string
	Value        string
}

type NetworksConfig struct {
	ID        int64
	NetworkID int64
	NodeID    sql.NullInt64
	Key       string
	Value     string
}

type NetworksForward struct {
	ID            int64
	NetworkID     int64
	NodeID        sql.NullInt64
	ListenAddress string
	Description   string
	Ports         string
}

type NetworksForwardsConfig struct {
	ID               int64
	NetworkForwardID int64
	Key              string
	Value            string
}

type NetworksLoadBalancer struct {
	ID            int64
	NetworkID     int64
	NodeID        sql.NullInt64
	ListenAddress string
	Description   string
	Backends      string
	Ports         string
}

type NetworksLoadBalancersConfig struct {
	ID                    int64
	NetworkLoadBalancerID int64
	Key                   string
	Value                 string
}

type NetworksNode struct {
	ID        int64
	NetworkID int64
	NodeID    int64
	State     int64
}

type NetworksPeer struct {
	ID                   int64
	NetworkID            int64
	Name                 string
	Description          string
	TargetNetworkProject interface{}
	TargetNetworkName    interface{}
	TargetNetworkID      interface{}
}

type NetworksPeersConfig struct {
	ID            int64
	NetworkPeerID int64
	Key           string
	Value         string
}

type NetworksZone struct {
	ID          int64
	ProjectID   int64
	Name        string
	Description string
}

type NetworksZonesConfig struct {
	ID            int64
	NetworkZoneID int64
	Key           string
	Value         string
}

type NetworksZonesRecord struct {
	ID            int64
	NetworkZoneID int64
	Name          string
	Description   string
	Entries       string
}

type NetworksZonesRecordsConfig struct {
	ID                  int64
	NetworkZoneRecordID int64
	Key                 string
	Value               string
}

type Node struct {
	ID              int64
	Name            string
	Description     string
	Address         string
	Schema          int64
	ApiExtensions   int64
	Heartbeat       sql.NullTime
	State           int64
	Arch            int64
	FailureDomainID sql.NullInt64
}

type NodesClusterGroup struct {
	ID      int64
	NodeID  int64
	GroupID int64
}

type NodesConfig struct {
	ID     int64
	NodeID int64
	Key    string
	Value  string
}

type NodesFailureDomain struct {
	ID   int64
	Name string
}

type NodesRole struct {
	NodeID int64
	Role   int64
}

type Operation struct {
	ID        int64
	Uuid      string
	NodeID    string
	Type      int64
	ProjectID sql.NullInt64
}

type Profile struct {
	ID          int64
	Name        string
	Description string
	ProjectID   int64
}

type ProfilesConfig struct {
	ID        int64
	ProfileID int64
	Key       string
	Value     string
}

type ProfilesDevice struct {
	ID        int64
	ProfileID int64
	Name      string
	Type      int64
}

type ProfilesDevicesConfig struct {
	ID              int64
	ProfileDeviceID int64
	Key             string
	Value           string
}

type Project struct {
	ID          int64
	Name        string
	Description string
}

type ProjectsConfig struct {
	ID        int64
	ProjectID int64
	Key       string
	Value     string
}

type StorageBucket struct {
	ID            int64
	Name          string
	StoragePoolID int64
	NodeID        sql.NullInt64
	Description   string
	ProjectID     int64
}

type StorageBucketsConfig struct {
	ID              int64
	StorageBucketID int64
	Key             string
	Value           string
}

type StorageBucketsKey struct {
	ID              int64
	StorageBucketID int64
	Name            string
	Description     string
	AccessKey       string
	SecretKey       string
	Role            string
}

type StoragePool struct {
	ID          int64
	Name        string
	Driver      string
	Description string
	State       int64
}

type StoragePoolsConfig struct {
	ID            int64
	StoragePoolID int64
	NodeID        sql.NullInt64
	Key           string
	Value         string
}

type StoragePoolsNode struct {
	ID            int64
	StoragePoolID int64
	NodeID        int64
	State         int64
}

type StorageVolume struct {
	ID            int64
	Name          string
	StoragePoolID int64
	NodeID        sql.NullInt64
	Type          int64
	Description   string
	ProjectID     int64
	ContentType   int64
	CreationDate  time.Time
}

type StorageVolumesAll struct {
	ID            int64
	Name          string
	StoragePoolID int64
	NodeID        sql.NullInt64
	Type          int64
	Description   string
	ProjectID     int64
	ContentType   int64
	CreationDate  time.Time
}

type StorageVolumesBackup struct {
	ID               int64
	StorageVolumeID  int64
	Name             string
	CreationDate     sql.NullTime
	ExpiryDate       sql.NullTime
	VolumeOnly       int64
	OptimizedStorage int64
}

type StorageVolumesConfig struct {
	ID              int64
	StorageVolumeID int64
	Key             string
	Value           string
}

type StorageVolumesSnapshot struct {
	ID              int64
	StorageVolumeID int64
	Name            string
	Description     string
	ExpiryDate      sql.NullTime
	CreationDate    time.Time
}

type StorageVolumesSnapshotsConfig struct {
	ID                      int64
	StorageVolumeSnapshotID int64
	Key                     string
	Value                   string
}

type Warning struct {
	ID             int64
	NodeID         sql.NullInt64
	ProjectID      sql.NullInt64
	EntityTypeCode sql.NullInt64
	EntityID       sql.NullInt64
	Uuid           string
	TypeCode       int64
	Status         int64
	FirstSeenDate  time.Time
	LastSeenDate   time.Time
	UpdatedDate    sql.NullTime
	LastMessage    string
	Count          int64
}
