//go:build linux && cgo && !agent

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package clustergen

import (
	"context"
	"strings"
	"time"

	"github.com/canonical/lxd/lxd/db/types"
)

const createAuthGroupPermission = `-- name: CreateAuthGroupPermission :exec
INSERT INTO auth_groups_permissions (auth_group_id, entity_type, entity_id, entitlement) VALUES (?, ?, ?, ?)
`

type CreateAuthGroupPermissionParams struct {
	AuthGroupID int64
	EntityType  types.EntityType
	EntityID    int64
	Entitlement string
}

func (q *Queries) CreateAuthGroupPermission(ctx context.Context, db DBTX, arg CreateAuthGroupPermissionParams) error {
	_, err := db.ExecContext(ctx, createAuthGroupPermission,
		arg.AuthGroupID,
		arg.EntityType,
		arg.EntityID,
		arg.Entitlement,
	)
	return err
}

const deleteAuthGroupPermissionsByAuthGroupID = `-- name: DeleteAuthGroupPermissionsByAuthGroupID :exec
DELETE FROM auth_groups_permissions WHERE auth_group_id = ?
`

func (q *Queries) DeleteAuthGroupPermissionsByAuthGroupID(ctx context.Context, db DBTX, authGroupID int64) error {
	_, err := db.ExecContext(ctx, deleteAuthGroupPermissionsByAuthGroupID, authGroupID)
	return err
}

const getAllAuthGroupPermissionsByGroupNames = `-- name: GetAllAuthGroupPermissionsByGroupNames :many
SELECT auth_groups.name AS group_name, auth_groups_permissions.id, auth_groups_permissions.auth_group_id, auth_groups_permissions.entity_type, auth_groups_permissions.entity_id, auth_groups_permissions.entitlement
    FROM auth_groups
    JOIN auth_groups_permissions ON auth_groups_permissions.auth_group_id = auth_groups.id
`

type GetAllAuthGroupPermissionsByGroupNamesRow struct {
	GroupName   string
	ID          int64
	AuthGroupID int64
	EntityType  types.EntityType
	EntityID    int64
	Entitlement string
}

func (q *Queries) GetAllAuthGroupPermissionsByGroupNames(ctx context.Context, db DBTX) ([]GetAllAuthGroupPermissionsByGroupNamesRow, error) {
	rows, err := db.QueryContext(ctx, getAllAuthGroupPermissionsByGroupNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAuthGroupPermissionsByGroupNamesRow
	for rows.Next() {
		var i GetAllAuthGroupPermissionsByGroupNamesRow
		if err := rows.Scan(
			&i.GroupName,
			&i.ID,
			&i.AuthGroupID,
			&i.EntityType,
			&i.EntityID,
			&i.Entitlement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllIdentitiesByAuthGroupIDs = `-- name: GetAllIdentitiesByAuthGroupIDs :many
SELECT identities_auth_groups.auth_group_id, identities.id, identities.auth_method, identities.type, identities.identifier, identities.name, identities.metadata, identities.first_seen_date, identities.last_seen_date, identities.updated_date
    FROM identities
    JOIN identities_auth_groups ON identities.id = identities_auth_groups.identity_id
`

type GetAllIdentitiesByAuthGroupIDsRow struct {
	AuthGroupID   int64
	ID            int64
	AuthMethod    types.AuthMethod
	Type          types.IdentityType
	Identifier    string
	Name          string
	Metadata      string
	FirstSeenDate time.Time
	LastSeenDate  time.Time
	UpdatedDate   time.Time
}

func (q *Queries) GetAllIdentitiesByAuthGroupIDs(ctx context.Context, db DBTX) ([]GetAllIdentitiesByAuthGroupIDsRow, error) {
	rows, err := db.QueryContext(ctx, getAllIdentitiesByAuthGroupIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllIdentitiesByAuthGroupIDsRow
	for rows.Next() {
		var i GetAllIdentitiesByAuthGroupIDsRow
		if err := rows.Scan(
			&i.AuthGroupID,
			&i.ID,
			&i.AuthMethod,
			&i.Type,
			&i.Identifier,
			&i.Name,
			&i.Metadata,
			&i.FirstSeenDate,
			&i.LastSeenDate,
			&i.UpdatedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllIdentityProviderGroupsByAuthGroupIDs = `-- name: GetAllIdentityProviderGroupsByAuthGroupIDs :many
SELECT auth_groups_identity_provider_groups.auth_group_id, identity_provider_groups.id, identity_provider_groups.name
    FROM identity_provider_groups
    JOIN auth_groups_identity_provider_groups ON identity_provider_groups.id = auth_groups_identity_provider_groups.identity_provider_group_id
`

type GetAllIdentityProviderGroupsByAuthGroupIDsRow struct {
	AuthGroupID int64
	ID          int64
	Name        string
}

func (q *Queries) GetAllIdentityProviderGroupsByAuthGroupIDs(ctx context.Context, db DBTX) ([]GetAllIdentityProviderGroupsByAuthGroupIDsRow, error) {
	rows, err := db.QueryContext(ctx, getAllIdentityProviderGroupsByAuthGroupIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllIdentityProviderGroupsByAuthGroupIDsRow
	for rows.Next() {
		var i GetAllIdentityProviderGroupsByAuthGroupIDsRow
		if err := rows.Scan(&i.AuthGroupID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthGroupNamesWithPermission = `-- name: GetAuthGroupNamesWithPermission :many
SELECT auth_groups.name
    FROM auth_groups_permissions
    JOIN auth_groups ON auth_groups_permissions.auth_group_id = auth_groups.id
WHERE auth_groups_permissions.entitlement = ? AND auth_groups_permissions.entity_type = ? AND auth_groups_permissions.entity_id = ?
`

type GetAuthGroupNamesWithPermissionParams struct {
	Entitlement string
	EntityType  types.EntityType
	EntityID    int64
}

func (q *Queries) GetAuthGroupNamesWithPermission(ctx context.Context, db DBTX, arg GetAuthGroupNamesWithPermissionParams) ([]string, error) {
	rows, err := db.QueryContext(ctx, getAuthGroupNamesWithPermission, arg.Entitlement, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthGroupPermissions = `-- name: GetAuthGroupPermissions :many
SELECT auth_groups_permissions.id, auth_groups_permissions.auth_group_id, auth_groups_permissions.entity_type, auth_groups_permissions.entity_id, auth_groups_permissions.entitlement
    FROM auth_groups_permissions
`

func (q *Queries) GetAuthGroupPermissions(ctx context.Context, db DBTX) ([]AuthGroupsPermission, error) {
	rows, err := db.QueryContext(ctx, getAuthGroupPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthGroupsPermission
	for rows.Next() {
		var i AuthGroupsPermission
		if err := rows.Scan(
			&i.ID,
			&i.AuthGroupID,
			&i.EntityType,
			&i.EntityID,
			&i.Entitlement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthGroupPermissionsByAuthGroupID = `-- name: GetAuthGroupPermissionsByAuthGroupID :many
SELECT auth_groups_permissions.id, auth_groups_permissions.auth_group_id, auth_groups_permissions.entity_type, auth_groups_permissions.entity_id, auth_groups_permissions.entitlement
    FROM auth_groups_permissions
    WHERE auth_groups_permissions.auth_group_id = ?
`

func (q *Queries) GetAuthGroupPermissionsByAuthGroupID(ctx context.Context, db DBTX, authGroupID int64) ([]AuthGroupsPermission, error) {
	rows, err := db.QueryContext(ctx, getAuthGroupPermissionsByAuthGroupID, authGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthGroupsPermission
	for rows.Next() {
		var i AuthGroupsPermission
		if err := rows.Scan(
			&i.ID,
			&i.AuthGroupID,
			&i.EntityType,
			&i.EntityID,
			&i.Entitlement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthGroupPermissionsWithEntityTypeAndEntitlementAndGroupName = `-- name: GetAuthGroupPermissionsWithEntityTypeAndEntitlementAndGroupName :many
SELECT auth_groups_permissions.id, auth_groups_permissions.auth_group_id, auth_groups_permissions.entity_type, auth_groups_permissions.entity_id, auth_groups_permissions.entitlement
    FROM auth_groups_permissions
    JOIN auth_groups ON auth_groups_permissions.auth_group_id = auth_groups.id
    WHERE auth_groups_permissions.entitlement = ? AND auth_groups_permissions.entity_type = ? AND auth_groups.name = ?
`

type GetAuthGroupPermissionsWithEntityTypeAndEntitlementAndGroupNameParams struct {
	Entitlement string
	EntityType  types.EntityType
	Name        string
}

func (q *Queries) GetAuthGroupPermissionsWithEntityTypeAndEntitlementAndGroupName(ctx context.Context, db DBTX, arg GetAuthGroupPermissionsWithEntityTypeAndEntitlementAndGroupNameParams) ([]AuthGroupsPermission, error) {
	rows, err := db.QueryContext(ctx, getAuthGroupPermissionsWithEntityTypeAndEntitlementAndGroupName, arg.Entitlement, arg.EntityType, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthGroupsPermission
	for rows.Next() {
		var i AuthGroupsPermission
		if err := rows.Scan(
			&i.ID,
			&i.AuthGroupID,
			&i.EntityType,
			&i.EntityID,
			&i.Entitlement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctPermissionsByGroupNames = `-- name: GetDistinctPermissionsByGroupNames :many
SELECT DISTINCT auth_groups_permissions.id, auth_groups_permissions.auth_group_id, auth_groups_permissions.entity_type, auth_groups_permissions.entity_id, auth_groups_permissions.entitlement
    FROM auth_groups_permissions
    JOIN auth_groups ON auth_groups_permissions.auth_group_id = auth_groups.id
    WHERE auth_groups.name IN (/*SLICE:groupNames*/?)
`

func (q *Queries) GetDistinctPermissionsByGroupNames(ctx context.Context, db DBTX, groupnames []string) ([]AuthGroupsPermission, error) {
	query := getDistinctPermissionsByGroupNames
	var queryParams []interface{}
	if len(groupnames) > 0 {
		for _, v := range groupnames {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:groupNames*/?", strings.Repeat(",?", len(groupnames))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:groupNames*/?", "NULL", 1)
	}
	rows, err := db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthGroupsPermission
	for rows.Next() {
		var i AuthGroupsPermission
		if err := rows.Scan(
			&i.ID,
			&i.AuthGroupID,
			&i.EntityType,
			&i.EntityID,
			&i.Entitlement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdentitiesByAuthGroupID = `-- name: GetIdentitiesByAuthGroupID :many
SELECT identities.id, identities.auth_method, identities.type, identities.identifier, identities.name, identities.metadata, identities.first_seen_date, identities.last_seen_date, identities.updated_date
FROM identities
    JOIN identities_auth_groups ON identities.id = identities_auth_groups.identity_id
    WHERE identities_auth_groups.auth_group_id = ?
`

func (q *Queries) GetIdentitiesByAuthGroupID(ctx context.Context, db DBTX, authGroupID int64) ([]Identity, error) {
	rows, err := db.QueryContext(ctx, getIdentitiesByAuthGroupID, authGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Identity
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.AuthMethod,
			&i.Type,
			&i.Identifier,
			&i.Name,
			&i.Metadata,
			&i.FirstSeenDate,
			&i.LastSeenDate,
			&i.UpdatedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdentityProviderGroupsByAuthGroupID = `-- name: GetIdentityProviderGroupsByAuthGroupID :many
SELECT identity_provider_groups.id, identity_provider_groups.name
    FROM identity_provider_groups
    JOIN auth_groups_identity_provider_groups ON identity_provider_groups.id = auth_groups_identity_provider_groups.identity_provider_group_id
    WHERE auth_groups_identity_provider_groups.auth_group_id = ?
`

func (q *Queries) GetIdentityProviderGroupsByAuthGroupID(ctx context.Context, db DBTX, authGroupID int64) ([]IdentityProviderGroup, error) {
	rows, err := db.QueryContext(ctx, getIdentityProviderGroupsByAuthGroupID, authGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityProviderGroup
	for rows.Next() {
		var i IdentityProviderGroup
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
