package schema

import (
	"database/sql"
	"fmt"
	"os"

	_ "github.com/mattn/go-sqlite3" // For opening the in-memory database
)

// WriteSQL writes '<filename>' in the current directory, containing SQL statements that match the given schema updates.
//
// The <filename> contains a "flattened" render of all given updates and
// can be used to initialize brand new databases using Schema.Fresh().
func WriteSQL(updates map[int]Update, filename string) error {
	// Apply all the updates that we have on a pristine database and dump
	// the resulting schema.
	db, err := sql.Open("sqlite3", ":memory:")
	if err != nil {
		return fmt.Errorf("failed to open in-memory SQLite database: %w", err)
	}

	schema := NewFromMap(updates)

	_, err = schema.Ensure(db)
	if err != nil {
		return err
	}

	dump, err := schema.Dump(db)
	if err != nil {
		return err
	}

	file, err := os.Create(filename)
	if err != nil {
		return fmt.Errorf("failed to open file for writing: %w", err)
	}

	_, err = file.Write([]byte(schemaFileHeader + "\n" + dump))
	if err != nil {
		return fmt.Errorf("failed to write to file: %w", err)
	}

	return nil
}

// Template for schema files (can't use backticks since we need to use backticks
// inside the template itself).
const schemaFileHeader = `-- DO NOT EDIT BY HAND
-- This code was generated by the schema.WriteSQL function. If you need to
-- modify the database schema, please add a new schema update to update.go
-- and the run 'make update-schema'
`
