// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

import (
	"github.com/canonical/lxd/lxd/auth"
	"github.com/canonical/lxd/lxd/shadowapi/types"
)

// WithEntitlements is generated from api.WithEntitlements - DO NOT EDIT!
type WithEntitlements struct {
	AccessEntitlements []auth.Entitlement `json:"access_entitlements,omitempty" yaml:"access_entitlements,omitempty" shadow:"auth_entitlements"`
}

// Identity is generated from api.Identity - DO NOT EDIT!
type Identity struct {
	WithEntitlements     `yaml:",inline"`
	AuthenticationMethod string                   `json:"authentication_method" yaml:"authentication_method"`
	Type                 string                   `json:"type" yaml:"type"`
	Identifier           string                   `json:"id" yaml:"id"`
	Name                 string                   `json:"name" yaml:"name"`
	Groups               []string                 `json:"groups" yaml:"groups"`
	TLSCertificate       types.X509CertificatePEM `json:"tls_certificate" yaml:"tls_certificate" shadow:"pem_encoded_x509_certificate"`
}

func (i Identity) Writable() IdentityPut {
	return IdentityPut{
		Groups:         i.Groups,
		TLSCertificate: i.TLSCertificate,
	}
}

func (i *Identity) SetWritable(put IdentityPut) {
	i.Groups = put.Groups
	i.TLSCertificate = put.TLSCertificate
}

// IdentityInfo is generated from api.IdentityInfo - DO NOT EDIT!
type IdentityInfo struct {
	Identity             `yaml:",inline"`
	EffectiveGroups      []string     `json:"effective_groups" yaml:"effective_groups"`
	EffectivePermissions []Permission `json:"effective_permissions" yaml:"effective_permissions"`
	FineGrained          bool         `json:"fine_grained" yaml:"fine_grained"`
}

// IdentityPut is generated from api.IdentityPut - DO NOT EDIT!
type IdentityPut struct {
	Groups         []string                 `json:"groups" yaml:"groups"`
	TLSCertificate types.X509CertificatePEM `json:"tls_certificate" yaml:"tls_certificate" shadow:"pem_encoded_x509_certificate"`
}

// IdentitiesTLSPost is generated from api.IdentitiesTLSPost - DO NOT EDIT!
type IdentitiesTLSPost struct {
	Name        string                   `json:"name" yaml:"name"`
	TrustToken  string                   `json:"trust_token" yaml:"trust_token"`
	Token       bool                     `json:"token" yaml:"token"`
	Certificate types.X509CertificatePEM `json:"certificate" yaml:"certificate" shadow:"pem_encoded_x509_certificate"`
	Groups      []string                 `json:"groups" yaml:"groups"`
}

// AuthGroup is generated from api.AuthGroup - DO NOT EDIT!
type AuthGroup struct {
	WithEntitlements       `yaml:",inline"`
	Name                   string              `json:"name" yaml:"name"`
	Description            string              `json:"description" yaml:"description"`
	Permissions            []Permission        `json:"permissions" yaml:"permissions"`
	Identities             map[string][]string `json:"identities" yaml:"identities"`
	IdentityProviderGroups []string            `json:"identity_provider_groups" yaml:"identity_provider_groups"`
}

func (g AuthGroup) Writable() AuthGroupPut {
	return AuthGroupPut{
		Description: g.Description,
		Permissions: g.Permissions,
	}
}

func (g *AuthGroup) SetWritable(put AuthGroupPut) {
	g.Description = put.Description
	g.Permissions = put.Permissions
}

// AuthGroupsPost is generated from api.AuthGroupsPost - DO NOT EDIT!
type AuthGroupsPost struct {
	AuthGroupPost `yaml:",inline"`
	AuthGroupPut  `yaml:",inline"`
}

// AuthGroupPost is generated from api.AuthGroupPost - DO NOT EDIT!
type AuthGroupPost struct {
	Name string `json:"name" yaml:"name"`
}

// AuthGroupPut is generated from api.AuthGroupPut - DO NOT EDIT!
type AuthGroupPut struct {
	Description string       `json:"description" yaml:"description"`
	Permissions []Permission `json:"permissions" yaml:"permissions"`
}

// IdentityProviderGroup is generated from api.IdentityProviderGroup - DO NOT EDIT!
type IdentityProviderGroup struct {
	WithEntitlements `yaml:",inline"`
	Name             string   `json:"name" yaml:"name"`
	Groups           []string `json:"groups" yaml:"groups"`
}

func (ipg IdentityProviderGroup) Writable() IdentityProviderGroupPut {
	return IdentityProviderGroupPut{
		Groups: ipg.Groups,
	}
}

func (ipg *IdentityProviderGroup) SetWritable(put IdentityProviderGroupPut) {
	ipg.Groups = put.Groups
}

// IdentityProviderGroupPost is generated from api.IdentityProviderGroupPost - DO NOT EDIT!
type IdentityProviderGroupPost struct {
	Name string `json:"name" yaml:"name"`
}

// IdentityProviderGroupPut is generated from api.IdentityProviderGroupPut - DO NOT EDIT!
type IdentityProviderGroupPut struct {
	Groups []string `json:"groups" yaml:"groups"`
}

// Permission is generated from api.Permission - DO NOT EDIT!
type Permission struct {
	EntityType      string `json:"entity_type" yaml:"entity_type"`
	EntityReference string `json:"url" yaml:"url"`
	Entitlement     string `json:"entitlement" yaml:"entitlement"`
}

// PermissionInfo is generated from api.PermissionInfo - DO NOT EDIT!
type PermissionInfo struct {
	Permission `yaml:",inline"`
	Groups     []string `json:"groups" yaml:"groups"`
}
