// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

import (
	"encoding/base64"
	"encoding/json"
	"time"

	"github.com/canonical/lxd/lxd/certificate"
	"github.com/canonical/lxd/lxd/shadowapi/types"
)

// CertificatesPost is generated from api.CertificatesPost - DO NOT EDIT!
type CertificatesPost struct {
	Name        string                      `json:"name" yaml:"name"`
	Type        certificate.Type            `json:"type" yaml:"type" shadow:"certificate_type"`
	Restricted  bool                        `json:"restricted" yaml:"restricted"`
	Projects    []string                    `json:"projects" yaml:"projects"`
	Certificate types.X509CertificateBase64 `json:"certificate" yaml:"certificate" shadow:"base64_encoded_x509_certificate"`
	Password    string                      `json:"password" yaml:"password"`
	TrustToken  string                      `json:"trust_token" yaml:"trust_token"`
	Token       bool                        `json:"token" yaml:"token"`
}

// CertificatePut is generated from api.CertificatePut - DO NOT EDIT!
type CertificatePut struct {
	Name        string                   `json:"name" yaml:"name"`
	Type        certificate.Type         `json:"type" yaml:"type" shadow:"certificate_type"`
	Restricted  bool                     `json:"restricted" yaml:"restricted"`
	Projects    []string                 `json:"projects" yaml:"projects"`
	Certificate types.X509CertificatePEM `json:"certificate" yaml:"certificate" shadow:"pem_encoded_x509_certificate"`
}

// Certificate is generated from api.Certificate - DO NOT EDIT!
type Certificate struct {
	WithEntitlements `yaml:",inline"`
	Name             string                   `json:"name" yaml:"name"`
	Type             certificate.Type         `json:"type" yaml:"type" shadow:"certificate_type"`
	Restricted       bool                     `json:"restricted" yaml:"restricted"`
	Projects         []string                 `json:"projects" yaml:"projects"`
	Certificate      types.X509CertificatePEM `json:"certificate" yaml:"certificate" shadow:"pem_encoded_x509_certificate"`
	Fingerprint      string                   `json:"fingerprint" yaml:"fingerprint"`
}

func (c *Certificate) Writable() CertificatePut {
	return CertificatePut{
		Name:        c.Name,
		Type:        c.Type,
		Restricted:  c.Restricted,
		Projects:    c.Projects,
		Certificate: c.Certificate,
	}
}

func (c *Certificate) SetWritable(put CertificatePut) {
	c.Name = put.Name
	c.Type = put.Type
	c.Restricted = put.Restricted
	c.Projects = put.Projects
	c.Certificate = put.Certificate
}

// CertificateAddToken is generated from api.CertificateAddToken - DO NOT EDIT!
type CertificateAddToken struct {
	ClientName  string    `json:"client_name" yaml:"client_name"`
	Fingerprint string    `json:"fingerprint" yaml:"fingerprint"`
	Addresses   []string  `json:"addresses" yaml:"addresses"`
	Secret      string    `json:"secret" yaml:"secret"`
	ExpiresAt   time.Time `json:"expires_at" yaml:"expires_at"`
	Type        string    `json:"type" yaml:"type"`
}

func (t *CertificateAddToken) String() string {
	joinTokenJSON, err := json.Marshal(t)
	if err != nil {
		return ""
	}

	return base64.StdEncoding.EncodeToString(joinTokenJSON)
}
