// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

import (
	"encoding/base64"
	"encoding/json"
	"time"
)

// Cluster is generated from api.Cluster - DO NOT EDIT!
type Cluster struct {
	ServerName   string                   `json:"server_name" yaml:"server_name"`
	Enabled      bool                     `json:"enabled" yaml:"enabled"`
	MemberConfig []ClusterMemberConfigKey `json:"member_config" yaml:"member_config"`
}

// ClusterMemberConfigKey is generated from api.ClusterMemberConfigKey - DO NOT EDIT!
type ClusterMemberConfigKey struct {
	Entity      string `json:"entity" yaml:"entity"`
	Name        string `json:"name" yaml:"name"`
	Key         string `json:"key" yaml:"key"`
	Value       string `json:"value" yaml:"value"`
	Description string `json:"description" yaml:"description"`
}

// ClusterPut is generated from api.ClusterPut - DO NOT EDIT!
type ClusterPut struct {
	Cluster            `yaml:",inline"`
	ClusterAddress     string `json:"cluster_address" yaml:"cluster_address"`
	ClusterCertificate string `json:"cluster_certificate" yaml:"cluster_certificate"`
	ServerAddress      string `json:"server_address" yaml:"server_address"`
	ClusterToken       string `json:"cluster_token" yaml:"cluster_token"`
}

// ClusterMembersPost is generated from api.ClusterMembersPost - DO NOT EDIT!
type ClusterMembersPost struct {
	ServerName string `json:"server_name" yaml:"server_name"`
}

// ClusterMemberJoinToken is generated from api.ClusterMemberJoinToken - DO NOT EDIT!
type ClusterMemberJoinToken struct {
	ServerName  string    `json:"server_name" yaml:"server_name"`
	Fingerprint string    `json:"fingerprint" yaml:"fingerprint"`
	Addresses   []string  `json:"addresses" yaml:"addresses"`
	Secret      string    `json:"secret" yaml:"secret"`
	ExpiresAt   time.Time `json:"expires_at" yaml:"expires_at"`
}

func (t *ClusterMemberJoinToken) String() string {
	joinTokenJSON, err := json.Marshal(t)
	if err != nil {
		return ""
	}

	return base64.StdEncoding.EncodeToString(joinTokenJSON)
}

// ClusterMemberPost is generated from api.ClusterMemberPost - DO NOT EDIT!
type ClusterMemberPost struct {
	ServerName string `json:"server_name" yaml:"server_name"`
}

// ClusterMember is generated from api.ClusterMember - DO NOT EDIT!
type ClusterMember struct {
	ServerName    string            `json:"server_name" yaml:"server_name"`
	URL           string            `json:"url" yaml:"url"`
	Database      bool              `json:"database" yaml:"database"`
	Status        string            `json:"status" yaml:"status"`
	Message       string            `json:"message" yaml:"message"`
	Architecture  string            `json:"architecture" yaml:"architecture"`
	Roles         []string          `json:"roles" yaml:"roles"`
	FailureDomain string            `json:"failure_domain" yaml:"failure_domain"`
	Description   string            `json:"description" yaml:"description"`
	Config        map[string]string `json:"config" yaml:"config"`
	Groups        []string          `json:"groups" yaml:"groups"`
}

func (member *ClusterMember) Writable() ClusterMemberPut {
	return ClusterMemberPut{
		Description:   member.Description,
		FailureDomain: member.FailureDomain,
		Roles:         member.Roles,
		Config:        member.Config,
		Groups:        member.Groups,
	}
}

// ClusterMemberPut is generated from api.ClusterMemberPut - DO NOT EDIT!
type ClusterMemberPut struct {
	Roles         []string          `json:"roles" yaml:"roles"`
	FailureDomain string            `json:"failure_domain" yaml:"failure_domain"`
	Description   string            `json:"description" yaml:"description"`
	Config        map[string]string `json:"config" yaml:"config"`
	Groups        []string          `json:"groups" yaml:"groups"`
}

// ClusterCertificatePut is generated from api.ClusterCertificatePut - DO NOT EDIT!
type ClusterCertificatePut struct {
	ClusterCertificate    string `json:"cluster_certificate" yaml:"cluster_certificate"`
	ClusterCertificateKey string `json:"cluster_certificate_key" yaml:"cluster_certificate_key"`
}

// ClusterMemberStatePost is generated from api.ClusterMemberStatePost - DO NOT EDIT!
type ClusterMemberStatePost struct {
	Action string `json:"action" yaml:"action"`
	Mode   string `json:"mode" yaml:"mode"`
}

// ClusterGroupsPost is generated from api.ClusterGroupsPost - DO NOT EDIT!
type ClusterGroupsPost struct {
	ClusterGroupPut
	Name string `json:"name" yaml:"name"`
}

// ClusterGroup is generated from api.ClusterGroup - DO NOT EDIT!
type ClusterGroup struct {
	Name        string   `json:"name" yaml:"name"`
	Description string   `json:"description" yaml:"description"`
	Members     []string `json:"members" yaml:"members"`
}

// ClusterGroupPost is generated from api.ClusterGroupPost - DO NOT EDIT!
type ClusterGroupPost struct {
	Name string `json:"name" yaml:"name"`
}

// ClusterGroupPut is generated from api.ClusterGroupPut - DO NOT EDIT!
type ClusterGroupPut struct {
	Description string   `json:"description" yaml:"description"`
	Members     []string `json:"members" yaml:"members"`
}

func (c *ClusterGroup) Writable() ClusterGroupPut {
	return ClusterGroupPut{
		Description: c.Description,
		Members:     c.Members,
	}
}

func (c *ClusterGroup) SetWritable(put ClusterGroupPut) {
	c.Description = put.Description
	c.Members = put.Members
}
