// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

import (
	"time"
)

// ContainerSnapshotsPost is generated from api.ContainerSnapshotsPost - DO NOT EDIT!
type ContainerSnapshotsPost struct {
	Name      string     `json:"name" yaml:"name"`
	Stateful  bool       `json:"stateful" yaml:"stateful"`
	ExpiresAt *time.Time `json:"expires_at" yaml:"expires_at"`
}

// ContainerSnapshotPost is generated from api.ContainerSnapshotPost - DO NOT EDIT!
type ContainerSnapshotPost struct {
	Name      string               `json:"name" yaml:"name"`
	Migration bool                 `json:"migration" yaml:"migration"`
	Target    *ContainerPostTarget `json:"target" yaml:"target"`
	Live      bool                 `json:"live,omitempty" yaml:"live,omitempty"`
}

// ContainerSnapshotPut is generated from api.ContainerSnapshotPut - DO NOT EDIT!
type ContainerSnapshotPut struct {
	Architecture string                       `json:"architecture" yaml:"architecture"`
	Config       map[string]string            `json:"config" yaml:"config"`
	Devices      map[string]map[string]string `json:"devices" yaml:"devices"`
	Ephemeral    bool                         `json:"ephemeral" yaml:"ephemeral"`
	Profiles     []string                     `json:"profiles" yaml:"profiles"`
	ExpiresAt    time.Time                    `json:"expires_at" yaml:"expires_at"`
}

// ContainerSnapshot is generated from api.ContainerSnapshot - DO NOT EDIT!
type ContainerSnapshot struct {
	Name            string                       `json:"name" yaml:"name"`
	Stateful        bool                         `json:"stateful" yaml:"stateful"`
	Ephemeral       bool                         `json:"ephemeral" yaml:"ephemeral"`
	Architecture    string                       `json:"architecture" yaml:"architecture"`
	CreatedAt       time.Time                    `json:"created_at" yaml:"created_at"`
	ExpiresAt       time.Time                    `json:"expires_at" yaml:"expires_at"`
	LastUsedAt      time.Time                    `json:"last_used_at" yaml:"last_used_at"`
	Profiles        []string                     `json:"profiles" yaml:"profiles"`
	Config          map[string]string            `json:"config" yaml:"config"`
	Devices         map[string]map[string]string `json:"devices" yaml:"devices"`
	ExpandedConfig  map[string]string            `json:"expanded_config" yaml:"expanded_config"`
	ExpandedDevices map[string]map[string]string `json:"expanded_devices" yaml:"expanded_devices"`
}

func (c *ContainerSnapshot) Writable() ContainerSnapshotPut {
	return ContainerSnapshotPut{
		Architecture: c.Architecture,
		Ephemeral:    c.Ephemeral,
		ExpiresAt:    c.ExpiresAt,
		Profiles:     c.Profiles,
		Config:       c.Config,
		Devices:      c.Devices,
	}
}

func (c *ContainerSnapshot) SetWritable(put ContainerSnapshotPut) {
	c.Architecture = put.Architecture
	c.Ephemeral = put.Ephemeral
	c.ExpiresAt = put.ExpiresAt
	c.Profiles = put.Profiles
	c.Config = put.Config
	c.Devices = put.Devices
}
