// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

import (
	"time"

	"github.com/canonical/lxd/shared/api"
)

// ContainersPost is generated from api.ContainersPost - DO NOT EDIT!
type ContainersPost struct {
	ContainerPut `yaml:",inline"`
	Name         string          `json:"name" yaml:"name"`
	Source       ContainerSource `json:"source" yaml:"source"`
	InstanceType string          `json:"instance_type" yaml:"instance_type"`
}

// ContainerPost is generated from api.ContainerPost - DO NOT EDIT!
type ContainerPost struct {
	Name          string               `json:"name" yaml:"name"`
	Migration     bool                 `json:"migration" yaml:"migration"`
	Live          bool                 `json:"live" yaml:"live"`
	ContainerOnly bool                 `json:"container_only" yaml:"container_only"`
	Target        *ContainerPostTarget `json:"target" yaml:"target"`
}

// ContainerPostTarget is generated from api.ContainerPostTarget - DO NOT EDIT!
type ContainerPostTarget struct {
	Certificate string            `json:"certificate" yaml:"certificate"`
	Operation   string            `json:"operation,omitempty" yaml:"operation,omitempty"`
	Websockets  map[string]string `json:"secrets,omitempty" yaml:"secrets,omitempty"`
}

// ContainerPut is generated from api.ContainerPut - DO NOT EDIT!
type ContainerPut struct {
	Architecture string                       `json:"architecture" yaml:"architecture"`
	Config       map[string]string            `json:"config" yaml:"config"`
	Devices      map[string]map[string]string `json:"devices" yaml:"devices"`
	Ephemeral    bool                         `json:"ephemeral" yaml:"ephemeral"`
	Profiles     []string                     `json:"profiles" yaml:"profiles"`
	Restore      string                       `json:"restore,omitempty" yaml:"restore,omitempty"`
	Stateful     bool                         `json:"stateful" yaml:"stateful"`
	Description  string                       `json:"description" yaml:"description"`
}

// Container is generated from api.Container - DO NOT EDIT!
type Container struct {
	Architecture    string                       `json:"architecture" yaml:"architecture"`
	Config          map[string]string            `json:"config" yaml:"config"`
	Devices         map[string]map[string]string `json:"devices" yaml:"devices"`
	Ephemeral       bool                         `json:"ephemeral" yaml:"ephemeral"`
	Profiles        []string                     `json:"profiles" yaml:"profiles"`
	Stateful        bool                         `json:"stateful" yaml:"stateful"`
	Description     string                       `json:"description" yaml:"description"`
	CreatedAt       time.Time                    `json:"created_at" yaml:"created_at"`
	ExpandedConfig  map[string]string            `json:"expanded_config" yaml:"expanded_config"`
	ExpandedDevices map[string]map[string]string `json:"expanded_devices" yaml:"expanded_devices"`
	Name            string                       `json:"name" yaml:"name"`
	Status          string                       `json:"status" yaml:"status"`
	StatusCode      api.StatusCode               `json:"status_code" yaml:"status_code" shadow:"status_code"`
	LastUsedAt      time.Time                    `json:"last_used_at" yaml:"last_used_at"`
	Location        string                       `json:"location" yaml:"location"`
}

// ContainerFull is generated from api.ContainerFull - DO NOT EDIT!
type ContainerFull struct {
	Container `yaml:",inline"`
	Backups   []ContainerBackup   `json:"backups" yaml:"backups"`
	State     *ContainerState     `json:"state" yaml:"state"`
	Snapshots []ContainerSnapshot `json:"snapshots" yaml:"snapshots"`
}

func (c *Container) Writable() ContainerPut {
	return ContainerPut{
		Architecture: c.Architecture,
		Config:       c.Config,
		Devices:      c.Devices,
		Ephemeral:    c.Ephemeral,
		Profiles:     c.Profiles,
		Stateful:     c.Stateful,
		Description:  c.Description,
	}
}

func (c *Container) SetWritable(put ContainerPut) {
	c.Architecture = put.Architecture
	c.Config = put.Config
	c.Devices = put.Devices
	c.Ephemeral = put.Ephemeral
	c.Profiles = put.Profiles
	c.Stateful = put.Stateful
	c.Description = put.Description
}

func (c Container) IsActive() bool {
	switch c.StatusCode {
	case api.Stopped:
		return false
	case api.Error:
		return false
	default:
		return true
	}
}

// ContainerSource is generated from api.ContainerSource - DO NOT EDIT!
type ContainerSource struct {
	Type          string            `json:"type" yaml:"type"`
	Certificate   string            `json:"certificate" yaml:"certificate"`
	Alias         string            `json:"alias,omitempty" yaml:"alias,omitempty"`
	Fingerprint   string            `json:"fingerprint,omitempty" yaml:"fingerprint,omitempty"`
	Properties    map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
	Server        string            `json:"server,omitempty" yaml:"server,omitempty"`
	Secret        string            `json:"secret,omitempty" yaml:"secret,omitempty"`
	Protocol      string            `json:"protocol,omitempty" yaml:"protocol,omitempty"`
	BaseImage     string            `json:"base-image,omitempty" yaml:"base-image,omitempty"`
	Mode          string            `json:"mode,omitempty" yaml:"mode,omitempty"`
	Operation     string            `json:"operation,omitempty" yaml:"operation,omitempty"`
	Websockets    map[string]string `json:"secrets,omitempty" yaml:"secrets,omitempty"`
	Source        string            `json:"source,omitempty" yaml:"source,omitempty"`
	Live          bool              `json:"live,omitempty" yaml:"live,omitempty"`
	ContainerOnly bool              `json:"container_only,omitempty" yaml:"container_only,omitempty"`
	Refresh       bool              `json:"refresh,omitempty" yaml:"refresh,omitempty"`
	Project       string            `json:"project,omitempty" yaml:"project,omitempty"`
}
