// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

import (
	"github.com/canonical/lxd/shared/api"
)

// ContainerStatePut is generated from api.ContainerStatePut - DO NOT EDIT!
type ContainerStatePut struct {
	Action   string `json:"action" yaml:"action"`
	Timeout  int    `json:"timeout" yaml:"timeout"`
	Force    bool   `json:"force" yaml:"force"`
	Stateful bool   `json:"stateful" yaml:"stateful"`
}

// ContainerState is generated from api.ContainerState - DO NOT EDIT!
type ContainerState struct {
	Status     string                           `json:"status" yaml:"status"`
	StatusCode api.StatusCode                   `json:"status_code" yaml:"status_code" shadow:"status_code"`
	Disk       map[string]ContainerStateDisk    `json:"disk" yaml:"disk"`
	Memory     ContainerStateMemory             `json:"memory" yaml:"memory"`
	Network    map[string]ContainerStateNetwork `json:"network" yaml:"network"`
	Pid        int64                            `json:"pid" yaml:"pid"`
	Processes  int64                            `json:"processes" yaml:"processes"`
	CPU        ContainerStateCPU                `json:"cpu" yaml:"cpu"`
}

// ContainerStateDisk is generated from api.ContainerStateDisk - DO NOT EDIT!
type ContainerStateDisk struct {
	Usage int64 `json:"usage" yaml:"usage"`
}

// ContainerStateCPU is generated from api.ContainerStateCPU - DO NOT EDIT!
type ContainerStateCPU struct {
	Usage int64 `json:"usage" yaml:"usage"`
}

// ContainerStateMemory is generated from api.ContainerStateMemory - DO NOT EDIT!
type ContainerStateMemory struct {
	Usage         int64 `json:"usage" yaml:"usage"`
	UsagePeak     int64 `json:"usage_peak" yaml:"usage_peak"`
	SwapUsage     int64 `json:"swap_usage" yaml:"swap_usage"`
	SwapUsagePeak int64 `json:"swap_usage_peak" yaml:"swap_usage_peak"`
}

// ContainerStateNetwork is generated from api.ContainerStateNetwork - DO NOT EDIT!
type ContainerStateNetwork struct {
	Addresses []ContainerStateNetworkAddress `json:"addresses" yaml:"addresses"`
	Counters  ContainerStateNetworkCounters  `json:"counters" yaml:"counters"`
	Hwaddr    string                         `json:"hwaddr" yaml:"hwaddr"`
	HostName  string                         `json:"host_name" yaml:"host_name"`
	Mtu       int                            `json:"mtu" yaml:"mtu"`
	State     string                         `json:"state" yaml:"state"`
	Type      string                         `json:"type" yaml:"type"`
}

// ContainerStateNetworkAddress is generated from api.ContainerStateNetworkAddress - DO NOT EDIT!
type ContainerStateNetworkAddress struct {
	Family  string `json:"family" yaml:"family"`
	Address string `json:"address" yaml:"address"`
	Netmask string `json:"netmask" yaml:"netmask"`
	Scope   string `json:"scope" yaml:"scope"`
}

// ContainerStateNetworkCounters is generated from api.ContainerStateNetworkCounters - DO NOT EDIT!
type ContainerStateNetworkCounters struct {
	BytesReceived   int64 `json:"bytes_received" yaml:"bytes_received"`
	BytesSent       int64 `json:"bytes_sent" yaml:"bytes_sent"`
	PacketsReceived int64 `json:"packets_received" yaml:"packets_received"`
	PacketsSent     int64 `json:"packets_sent" yaml:"packets_sent"`
}
