// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

import (
	"time"
)

// ContainerBackupsPost is generated from api.ContainerBackupsPost - DO NOT EDIT!
type ContainerBackupsPost struct {
	Name             string    `json:"name" yaml:"name"`
	ExpiresAt        time.Time `json:"expires_at" yaml:"expires_at"`
	ContainerOnly    bool      `json:"container_only" yaml:"container_only"`
	OptimizedStorage bool      `json:"optimized_storage" yaml:"optimized_storage"`
}

// ContainerBackup is generated from api.ContainerBackup - DO NOT EDIT!
type ContainerBackup struct {
	Name             string    `json:"name" yaml:"name"`
	CreatedAt        time.Time `json:"created_at" yaml:"created_at"`
	ExpiresAt        time.Time `json:"expires_at" yaml:"expires_at"`
	ContainerOnly    bool      `json:"container_only" yaml:"container_only"`
	OptimizedStorage bool      `json:"optimized_storage" yaml:"optimized_storage"`
}

// ContainerBackupPost is generated from api.ContainerBackupPost - DO NOT EDIT!
type ContainerBackupPost struct {
	Name string `json:"name" yaml:"name"`
}
