// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

// ContainerConsoleControl is generated from api.ContainerConsoleControl - DO NOT EDIT!
type ContainerConsoleControl struct {
	Command string            `json:"command" yaml:"command"`
	Args    map[string]string `json:"args" yaml:"args"`
}

// ContainerConsolePost is generated from api.ContainerConsolePost - DO NOT EDIT!
type ContainerConsolePost struct {
	Width  int `json:"width" yaml:"width"`
	Height int `json:"height" yaml:"height"`
}
