// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

// DevLXDPut is generated from api.DevLXDPut - DO NOT EDIT!
type DevLXDPut struct {
	State string `json:"state" yaml:"state"`
}

// DevLXDGet is generated from api.DevLXDGet - DO NOT EDIT!
type DevLXDGet struct {
	DevLXDPut
	APIVersion   string `json:"api_version" yaml:"api_version"`
	InstanceType string `json:"instance_type" yaml:"instance_type"`
	Location     string `json:"location" yaml:"location"`
}

// UbuntuProGuestTokenResponse is generated from api.UbuntuProGuestTokenResponse - DO NOT EDIT!
type UbuntuProGuestTokenResponse struct {
	Expires    string `json:"expires"`
	GuestToken string `json:"guest_token"`
	ID         string `json:"id"`
}

// UbuntuProSettings is generated from api.UbuntuProSettings - DO NOT EDIT!
type UbuntuProSettings struct {
	GuestAttach string `json:"guest_attach"`
}
