// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/canonical/lxd/shared/api"
)

// Event is generated from api.Event - DO NOT EDIT!
type Event struct {
	Type      string          `yaml:"type" json:"type"`
	Timestamp time.Time       `yaml:"timestamp" json:"timestamp"`
	Metadata  json.RawMessage `yaml:"metadata" json:"metadata"`
	Location  string          `yaml:"location,omitempty" json:"location,omitempty"`
	Project   string          `yaml:"project,omitempty" json:"project,omitempty"`
}

func (event *Event) ToLogging() (EventLogRecord, error) {
	if event.Type == api.EventTypeLogging || event.Type == api.EventTypeOVN {
		e := &EventLogging{}
		err := json.Unmarshal(event.Metadata, &e)
		if err != nil {
			return EventLogRecord{}, err
		}

		ctx := []any{}
		for k, v := range e.Context {
			ctx = append(ctx, k)
			ctx = append(ctx, v)
		}

		record := EventLogRecord{
			Time: event.Timestamp,
			Lvl:  e.Level,
			Msg:  e.Message,
			Ctx:  ctx,
		}

		return record, nil
	} else if event.Type == api.EventTypeLifecycle {
		e := &EventLifecycle{}
		err := json.Unmarshal(event.Metadata, &e)
		if err != nil {
			return EventLogRecord{}, err
		}

		ctx := []any{}
		for k, v := range e.Context {
			ctx = append(ctx, k)
			ctx = append(ctx, v)
		}

		record := EventLogRecord{
			Time: event.Timestamp,
			Lvl:  "info",
			Ctx:  ctx,
		}

		if e.Requestor != nil {
			requestor := e.Requestor.Protocol + "/" + e.Requestor.Username + " (" + e.Requestor.Address + ")"
			record.Msg = "Action: " + e.Action + ", Source: " + e.Source + ", Requestor: " + requestor
		} else {
			record.Msg = "Action: " + e.Action + ", Source: " + e.Source
		}

		return record, nil
	} else if event.Type == api.EventTypeOperation {
		e := &Operation{}
		err := json.Unmarshal(event.Metadata, &e)
		if err != nil {
			return EventLogRecord{}, err
		}

		record := EventLogRecord{
			Time: event.Timestamp,
			Lvl:  "info",
			Msg:  "ID: " + e.ID + ", Class: " + e.Class + ", Description: " + e.Description,
			Ctx: []any{
				"CreatedAt", e.CreatedAt,
				"UpdatedAt", e.UpdatedAt,
				"Status", e.Status,
				"StatusCode", e.StatusCode,
				"Resources", e.Resources,
				"Metadata", e.Metadata,
				"MayCancel", e.MayCancel,
				"Err", e.Err,
				"Location", e.Location,
			},
		}

		return record, nil
	}

	return EventLogRecord{}, fmt.Errorf("Not supported event type: %s", event.Type)
}

// EventLogRecord is generated from api.EventLogRecord - DO NOT EDIT!
type EventLogRecord struct {
	Time time.Time
	Lvl  string
	Msg  string
	Ctx  []any
}

// EventLogging is generated from api.EventLogging - DO NOT EDIT!
type EventLogging struct {
	Message string            `yaml:"message" json:"message"`
	Level   string            `yaml:"level" json:"level"`
	Context map[string]string `yaml:"context" json:"context"`
}

// EventLifecycle is generated from api.EventLifecycle - DO NOT EDIT!
type EventLifecycle struct {
	Action    string                   `yaml:"action" json:"action"`
	Source    string                   `yaml:"source" json:"source"`
	Context   map[string]any           `yaml:"context,omitempty" json:"context,omitempty"`
	Requestor *EventLifecycleRequestor `yaml:"requestor,omitempty" json:"requestor,omitempty"`
	Name      string                   `yaml:"name,omitempty" json:"name,omitempty"`
	Project   string                   `yaml:"project,omitempty" json:"project,omitempty"`
}

// EventLifecycleRequestor is generated from api.EventLifecycleRequestor - DO NOT EDIT!
type EventLifecycleRequestor struct {
	Username string `yaml:"username" json:"username"`
	Protocol string `yaml:"protocol" json:"protocol"`
	Address  string `yaml:"address" json:"address"`
}
