// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

import (
	"time"
)

// ImageExportPost is generated from api.ImageExportPost - DO NOT EDIT!
type ImageExportPost struct {
	Target      string       `json:"target" yaml:"target"`
	Secret      string       `json:"secret" yaml:"secret"`
	Certificate string       `json:"certificate" yaml:"certificate"`
	Aliases     []ImageAlias `json:"aliases" yaml:"aliases"`
	Project     string       `json:"project" yaml:"project"`
	Profiles    []string     `json:"profiles" yaml:"profiles"`
}

// ImagesPost is generated from api.ImagesPost - DO NOT EDIT!
type ImagesPost struct {
	ImagePut             `yaml:",inline"`
	Filename             string            `json:"filename" yaml:"filename"`
	Source               *ImagesPostSource `json:"source" yaml:"source"`
	CompressionAlgorithm string            `json:"compression_algorithm" yaml:"compression_algorithm"`
	Aliases              []ImageAlias      `json:"aliases" yaml:"aliases"`
}

// ImagesPostSource is generated from api.ImagesPostSource - DO NOT EDIT!
type ImagesPostSource struct {
	ImageSource `yaml:",inline"`
	Mode        string `json:"mode" yaml:"mode"`
	Type        string `json:"type" yaml:"type"`
	URL         string `json:"url" yaml:"url"`
	Name        string `json:"name" yaml:"name"`
	Fingerprint string `json:"fingerprint" yaml:"fingerprint"`
	Secret      string `json:"secret" yaml:"secret"`
	Project     string `json:"project" yaml:"project"`
}

// ImagePut is generated from api.ImagePut - DO NOT EDIT!
type ImagePut struct {
	AutoUpdate bool              `json:"auto_update" yaml:"auto_update"`
	Properties map[string]string `json:"properties" yaml:"properties"`
	Public     bool              `json:"public" yaml:"public"`
	ExpiresAt  time.Time         `json:"expires_at" yaml:"expires_at"`
	Profiles   []string          `json:"profiles" yaml:"profiles"`
}

// Image is generated from api.Image - DO NOT EDIT!
type Image struct {
	WithEntitlements `yaml:",inline"`
	Aliases          []ImageAlias      `json:"aliases" yaml:"aliases"`
	Architecture     string            `json:"architecture" yaml:"architecture"`
	Cached           bool              `json:"cached" yaml:"cached"`
	Public           bool              `json:"public" yaml:"public"`
	Filename         string            `json:"filename" yaml:"filename"`
	Fingerprint      string            `json:"fingerprint" yaml:"fingerprint"`
	Size             int64             `json:"size" yaml:"size"`
	UpdateSource     *ImageSource      `json:"update_source,omitempty" yaml:"update_source,omitempty"`
	AutoUpdate       bool              `json:"auto_update" yaml:"auto_update"`
	Type             string            `json:"type" yaml:"type"`
	CreatedAt        time.Time         `json:"created_at" yaml:"created_at"`
	ExpiresAt        time.Time         `json:"expires_at" yaml:"expires_at"`
	LastUsedAt       time.Time         `json:"last_used_at" yaml:"last_used_at"`
	UploadedAt       time.Time         `json:"uploaded_at" yaml:"uploaded_at"`
	Properties       map[string]string `json:"properties" yaml:"properties"`
	Profiles         []string          `json:"profiles" yaml:"profiles"`
	Project          string            `json:"project" yaml:"project"`
}

func (img *Image) Writable() ImagePut {
	return ImagePut{
		AutoUpdate: img.AutoUpdate,
		Public:     img.Public,
		ExpiresAt:  img.ExpiresAt,
		Properties: img.Properties,
		Profiles:   img.Profiles,
	}
}

func (img *Image) SetWritable(put ImagePut) {
	img.AutoUpdate = put.AutoUpdate
	img.Public = put.Public
	img.ExpiresAt = put.ExpiresAt
	img.Properties = put.Properties
	img.Profiles = put.Profiles
}

// ImageAlias is generated from api.ImageAlias - DO NOT EDIT!
type ImageAlias struct {
	Name        string `json:"name" yaml:"name"`
	Description string `json:"description" yaml:"description"`
}

// ImageSource is generated from api.ImageSource - DO NOT EDIT!
type ImageSource struct {
	Alias       string `json:"alias" yaml:"alias"`
	Certificate string `json:"certificate" yaml:"certificate"`
	Protocol    string `json:"protocol" yaml:"protocol"`
	Server      string `json:"server" yaml:"server"`
	ImageType   string `json:"image_type" yaml:"image_type"`
}

// ImageAliasesPost is generated from api.ImageAliasesPost - DO NOT EDIT!
type ImageAliasesPost struct {
	ImageAliasesEntry `yaml:",inline"`
}

// ImageAliasesEntryPost is generated from api.ImageAliasesEntryPost - DO NOT EDIT!
type ImageAliasesEntryPost struct {
	Name string `json:"name" yaml:"name"`
}

// ImageAliasesEntryPut is generated from api.ImageAliasesEntryPut - DO NOT EDIT!
type ImageAliasesEntryPut struct {
	Description string `json:"description" yaml:"description"`
	Target      string `json:"target" yaml:"target"`
}

// ImageAliasesEntry is generated from api.ImageAliasesEntry - DO NOT EDIT!
type ImageAliasesEntry struct {
	WithEntitlements `yaml:",inline"`
	Name             string `json:"name" yaml:"name"`
	Description      string `json:"description" yaml:"description"`
	Type             string `json:"type" yaml:"type"`
	Target           string `json:"target" yaml:"target"`
}

// ImageMetadata is generated from api.ImageMetadata - DO NOT EDIT!
type ImageMetadata struct {
	Architecture string                            `json:"architecture" yaml:"architecture"`
	CreationDate int64                             `json:"creation_date" yaml:"creation_date"`
	ExpiryDate   int64                             `json:"expiry_date" yaml:"expiry_date"`
	Properties   map[string]string                 `json:"properties" yaml:"properties"`
	Templates    map[string]*ImageMetadataTemplate `json:"templates" yaml:"templates"`
}

// ImageMetadataTemplate is generated from api.ImageMetadataTemplate - DO NOT EDIT!
type ImageMetadataTemplate struct {
	When       []string          `json:"when" yaml:"when"`
	CreateOnly bool              `json:"create_only" yaml:"create_only"`
	Template   string            `json:"template" yaml:"template"`
	Properties map[string]string `json:"properties" yaml:"properties"`
}
