// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

// InitPreseed is generated from api.InitPreseed - DO NOT EDIT!
type InitPreseed struct {
	Node    InitLocalPreseed    `yaml:",inline"`
	Cluster *InitClusterPreseed `json:"cluster" yaml:"cluster"`
}

// InitLocalPreseed is generated from api.InitLocalPreseed - DO NOT EDIT!
type InitLocalPreseed struct {
	ServerPut      `yaml:",inline"`
	Networks       []InitNetworksProjectPost       `json:"networks" yaml:"networks"`
	StoragePools   []StoragePoolsPost              `json:"storage_pools" yaml:"storage_pools"`
	StorageVolumes []InitStorageVolumesProjectPost `json:"storage_volumes" yaml:"storage_volumes"`
	Profiles       []ProfilesPost                  `json:"profiles" yaml:"profiles"`
	Projects       []ProjectsPost                  `json:"projects" yaml:"projects"`
}

// InitNetworksProjectPost is generated from api.InitNetworksProjectPost - DO NOT EDIT!
type InitNetworksProjectPost struct {
	NetworksPost `yaml:",inline"`
	Project      string
}

// InitStorageVolumesProjectPost is generated from api.InitStorageVolumesProjectPost - DO NOT EDIT!
type InitStorageVolumesProjectPost struct {
	StorageVolumesPost `yaml:",inline"`
	Pool               string
	Project            string
}

// InitClusterPreseed is generated from api.InitClusterPreseed - DO NOT EDIT!
type InitClusterPreseed struct {
	ClusterPut             `yaml:",inline"`
	ClusterCertificatePath string `json:"cluster_certificate_path" yaml:"cluster_certificate_path"`
}
