// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

// InstanceConsoleControl is generated from api.InstanceConsoleControl - DO NOT EDIT!
type InstanceConsoleControl struct {
	Command string            `json:"command" yaml:"command"`
	Args    map[string]string `json:"args" yaml:"args"`
}

// InstanceConsolePost is generated from api.InstanceConsolePost - DO NOT EDIT!
type InstanceConsolePost struct {
	Width  int    `json:"width" yaml:"width"`
	Height int    `json:"height" yaml:"height"`
	Type   string `json:"type" yaml:"type"`
}
