// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

import (
	"github.com/canonical/lxd/shared/api"
)

// InstanceStatePut is generated from api.InstanceStatePut - DO NOT EDIT!
type InstanceStatePut struct {
	Action   string `json:"action" yaml:"action"`
	Timeout  int    `json:"timeout" yaml:"timeout"`
	Force    bool   `json:"force" yaml:"force"`
	Stateful bool   `json:"stateful" yaml:"stateful"`
}

// InstanceState is generated from api.InstanceState - DO NOT EDIT!
type InstanceState struct {
	Status     string                          `json:"status" yaml:"status"`
	StatusCode api.StatusCode                  `json:"status_code" yaml:"status_code" shadow:"status_code"`
	Disk       map[string]InstanceStateDisk    `json:"disk" yaml:"disk"`
	Memory     InstanceStateMemory             `json:"memory" yaml:"memory"`
	Network    map[string]InstanceStateNetwork `json:"network" yaml:"network"`
	Pid        int64                           `json:"pid" yaml:"pid"`
	Processes  int64                           `json:"processes" yaml:"processes"`
	CPU        InstanceStateCPU                `json:"cpu" yaml:"cpu"`
}

// InstanceStateDisk is generated from api.InstanceStateDisk - DO NOT EDIT!
type InstanceStateDisk struct {
	Usage int64 `json:"usage" yaml:"usage"`
	Total int64 `json:"total" yaml:"total"`
}

// InstanceStateCPU is generated from api.InstanceStateCPU - DO NOT EDIT!
type InstanceStateCPU struct {
	Usage int64 `json:"usage" yaml:"usage"`
}

// InstanceStateMemory is generated from api.InstanceStateMemory - DO NOT EDIT!
type InstanceStateMemory struct {
	Usage         int64 `json:"usage" yaml:"usage"`
	UsagePeak     int64 `json:"usage_peak" yaml:"usage_peak"`
	Total         int64 `json:"total" yaml:"total"`
	SwapUsage     int64 `json:"swap_usage" yaml:"swap_usage"`
	SwapUsagePeak int64 `json:"swap_usage_peak" yaml:"swap_usage_peak"`
}

// InstanceStateNetwork is generated from api.InstanceStateNetwork - DO NOT EDIT!
type InstanceStateNetwork struct {
	Addresses []InstanceStateNetworkAddress `json:"addresses" yaml:"addresses"`
	Counters  InstanceStateNetworkCounters  `json:"counters" yaml:"counters"`
	Hwaddr    string                        `json:"hwaddr" yaml:"hwaddr"`
	HostName  string                        `json:"host_name" yaml:"host_name"`
	Mtu       int                           `json:"mtu" yaml:"mtu"`
	State     string                        `json:"state" yaml:"state"`
	Type      string                        `json:"type" yaml:"type"`
}

// InstanceStateNetworkAddress is generated from api.InstanceStateNetworkAddress - DO NOT EDIT!
type InstanceStateNetworkAddress struct {
	Family  string `json:"family" yaml:"family"`
	Address string `json:"address" yaml:"address"`
	Netmask string `json:"netmask" yaml:"netmask"`
	Scope   string `json:"scope" yaml:"scope"`
}

// InstanceStateNetworkCounters is generated from api.InstanceStateNetworkCounters - DO NOT EDIT!
type InstanceStateNetworkCounters struct {
	BytesReceived          int64 `json:"bytes_received" yaml:"bytes_received"`
	BytesSent              int64 `json:"bytes_sent" yaml:"bytes_sent"`
	PacketsReceived        int64 `json:"packets_received" yaml:"packets_received"`
	PacketsSent            int64 `json:"packets_sent" yaml:"packets_sent"`
	ErrorsReceived         int64 `json:"errors_received" yaml:"errors_received"`
	ErrorsSent             int64 `json:"errors_sent" yaml:"errors_sent"`
	PacketsDroppedOutbound int64 `json:"packets_dropped_outbound" yaml:"packets_dropped_outbound"`
	PacketsDroppedInbound  int64 `json:"packets_dropped_inbound" yaml:"packets_dropped_inbound"`
}
