// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

import (
	"time"
)

// InstanceBackupsPost is generated from api.InstanceBackupsPost - DO NOT EDIT!
type InstanceBackupsPost struct {
	Name                 string    `json:"name" yaml:"name"`
	ExpiresAt            time.Time `json:"expires_at" yaml:"expires_at"`
	InstanceOnly         bool      `json:"instance_only" yaml:"instance_only"`
	ContainerOnly        bool      `json:"container_only" yaml:"container_only"`
	OptimizedStorage     bool      `json:"optimized_storage" yaml:"optimized_storage"`
	CompressionAlgorithm string    `json:"compression_algorithm" yaml:"compression_algorithm"`
}

// InstanceBackup is generated from api.InstanceBackup - DO NOT EDIT!
type InstanceBackup struct {
	Name             string    `json:"name" yaml:"name"`
	CreatedAt        time.Time `json:"created_at" yaml:"created_at"`
	ExpiresAt        time.Time `json:"expires_at" yaml:"expires_at"`
	InstanceOnly     bool      `json:"instance_only" yaml:"instance_only"`
	ContainerOnly    bool      `json:"container_only" yaml:"container_only"`
	OptimizedStorage bool      `json:"optimized_storage" yaml:"optimized_storage"`
}

// InstanceBackupPost is generated from api.InstanceBackupPost - DO NOT EDIT!
type InstanceBackupPost struct {
	Name string `json:"name" yaml:"name"`
}
