// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

import (
	"strings"
	"time"

	"github.com/canonical/lxd/lxd/instance/instancetype"
	"github.com/canonical/lxd/shared/api"
)

func GetParentAndSnapshotName(name string) (parentName string, snapshotName string, isSnapshot bool) {
	parentName, snapshotName, isSnapshot = strings.Cut(name, "/")
	if !isSnapshot {
		return name, "", isSnapshot
	}

	return parentName, snapshotName, isSnapshot
}

// InstancesPost is generated from api.InstancesPost - DO NOT EDIT!
type InstancesPost struct {
	InstancePut  `yaml:",inline"`
	Name         string            `json:"name" yaml:"name"`
	Source       InstanceSource    `json:"source" yaml:"source"`
	InstanceType string            `json:"instance_type" yaml:"instance_type"`
	Type         instancetype.Type `json:"type" yaml:"type" shadow:"instance_type"`
	Start        bool              `json:"start" yaml:"start"`
}

// InstancesPut is generated from api.InstancesPut - DO NOT EDIT!
type InstancesPut struct {
	State *InstanceStatePut `json:"state" yaml:"state"`
}

// InstancePost is generated from api.InstancePost - DO NOT EDIT!
type InstancePost struct {
	Name              string              `json:"name" yaml:"name"`
	Migration         bool                `json:"migration" yaml:"migration"`
	Live              bool                `json:"live" yaml:"live"`
	InstanceOnly      bool                `json:"instance_only" yaml:"instance_only"`
	ContainerOnly     bool                `json:"container_only" yaml:"container_only"`
	Target            *InstancePostTarget `json:"target" yaml:"target"`
	Pool              string              `json:"pool" yaml:"pool"`
	Project           string              `json:"project" yaml:"project"`
	AllowInconsistent bool                `json:"allow_inconsistent" yaml:"allow_inconsistent"`
	Config            map[string]string
	Devices           map[string]map[string]string
	Profiles          []string
}

// InstancePostTarget is generated from api.InstancePostTarget - DO NOT EDIT!
type InstancePostTarget struct {
	Certificate string            `json:"certificate" yaml:"certificate"`
	Operation   string            `json:"operation,omitempty" yaml:"operation,omitempty"`
	Websockets  map[string]string `json:"secrets,omitempty" yaml:"secrets,omitempty"`
}

// InstancePut is generated from api.InstancePut - DO NOT EDIT!
type InstancePut struct {
	Architecture string                       `json:"architecture" yaml:"architecture"`
	Config       map[string]string            `json:"config" yaml:"config"`
	Devices      map[string]map[string]string `json:"devices" yaml:"devices"`
	Ephemeral    bool                         `json:"ephemeral" yaml:"ephemeral"`
	Profiles     []string                     `json:"profiles" yaml:"profiles"`
	Restore      string                       `json:"restore,omitempty" yaml:"restore,omitempty"`
	Stateful     bool                         `json:"stateful" yaml:"stateful"`
	Description  string                       `json:"description" yaml:"description"`
}

// InstanceRebuildPost is generated from api.InstanceRebuildPost - DO NOT EDIT!
type InstanceRebuildPost struct {
	Source InstanceSource `json:"source" yaml:"source"`
}

// Instance is generated from api.Instance - DO NOT EDIT!
type Instance struct {
	WithEntitlements `yaml:",inline"`
	Name             string                       `json:"name" yaml:"name"`
	Description      string                       `json:"description" yaml:"description"`
	Status           string                       `json:"status" yaml:"status"`
	StatusCode       api.StatusCode               `json:"status_code" yaml:"status_code" shadow:"status_code"`
	CreatedAt        time.Time                    `json:"created_at" yaml:"created_at"`
	LastUsedAt       time.Time                    `json:"last_used_at" yaml:"last_used_at"`
	Location         string                       `json:"location" yaml:"location"`
	Type             string                       `json:"type" yaml:"type"`
	Project          string                       `json:"project" yaml:"project"`
	Architecture     string                       `json:"architecture" yaml:"architecture"`
	Ephemeral        bool                         `json:"ephemeral" yaml:"ephemeral"`
	Stateful         bool                         `json:"stateful" yaml:"stateful"`
	Profiles         []string                     `json:"profiles" yaml:"profiles"`
	Config           map[string]string            `json:"config" yaml:"config"`
	Devices          map[string]map[string]string `json:"devices" yaml:"devices"`
	ExpandedConfig   map[string]string            `json:"expanded_config,omitempty" yaml:"expanded_config,omitempty"`
	ExpandedDevices  map[string]map[string]string `json:"expanded_devices,omitempty" yaml:"expanded_devices,omitempty"`
}

// InstanceFull is generated from api.InstanceFull - DO NOT EDIT!
type InstanceFull struct {
	Instance  `yaml:",inline"`
	Backups   []InstanceBackup   `json:"backups" yaml:"backups"`
	State     *InstanceState     `json:"state" yaml:"state"`
	Snapshots []InstanceSnapshot `json:"snapshots" yaml:"snapshots"`
}

func (c *Instance) Writable() InstancePut {
	return InstancePut{
		Architecture: c.Architecture,
		Config:       c.Config,
		Devices:      c.Devices,
		Ephemeral:    c.Ephemeral,
		Profiles:     c.Profiles,
		Stateful:     c.Stateful,
		Description:  c.Description,
	}
}

func (c *Instance) SetWritable(put InstancePut) {
	c.Architecture = put.Architecture
	c.Config = put.Config
	c.Devices = put.Devices
	c.Ephemeral = put.Ephemeral
	c.Profiles = put.Profiles
	c.Stateful = put.Stateful
	c.Description = put.Description
}

func (c Instance) IsActive() bool {
	switch c.StatusCode {
	case api.Stopped:
		return false
	case api.Error:
		return false
	default:
		return true
	}
}

// InstanceSource is generated from api.InstanceSource - DO NOT EDIT!
type InstanceSource struct {
	Type              string            `json:"type" yaml:"type"`
	Certificate       string            `json:"certificate" yaml:"certificate"`
	Alias             string            `json:"alias,omitempty" yaml:"alias,omitempty"`
	Fingerprint       string            `json:"fingerprint,omitempty" yaml:"fingerprint,omitempty"`
	Properties        map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
	Server            string            `json:"server,omitempty" yaml:"server,omitempty"`
	Secret            string            `json:"secret,omitempty" yaml:"secret,omitempty"`
	Protocol          string            `json:"protocol,omitempty" yaml:"protocol,omitempty"`
	BaseImage         string            `json:"base-image,omitempty" yaml:"base-image,omitempty"`
	Mode              string            `json:"mode,omitempty" yaml:"mode,omitempty"`
	Operation         string            `json:"operation,omitempty" yaml:"operation,omitempty"`
	Websockets        map[string]string `json:"secrets,omitempty" yaml:"secrets,omitempty"`
	Source            string            `json:"source,omitempty" yaml:"source,omitempty"`
	Live              bool              `json:"live,omitempty" yaml:"live,omitempty"`
	InstanceOnly      bool              `json:"instance_only,omitempty" yaml:"instance_only,omitempty"`
	ContainerOnly     bool              `json:"container_only,omitempty" yaml:"container_only,omitempty"`
	Refresh           bool              `json:"refresh,omitempty" yaml:"refresh,omitempty"`
	Project           string            `json:"project,omitempty" yaml:"project,omitempty"`
	AllowInconsistent bool              `json:"allow_inconsistent" yaml:"allow_inconsistent"`
	SourceDiskSize    int64             `json:"source_disk_size" yaml:"source_disk_size"`
	ConversionOptions []string          `json:"conversion_options" yaml:"conversion_options"`
}

// InstanceUEFIVars is generated from api.InstanceUEFIVars - DO NOT EDIT!
type InstanceUEFIVars struct {
	Variables map[string]InstanceUEFIVariable `json:"variables" yaml:"variables"`
}

// InstanceUEFIVariable is generated from api.InstanceUEFIVariable - DO NOT EDIT!
type InstanceUEFIVariable struct {
	Data      string `json:"data" yaml:"data"`
	Attr      uint32 `json:"attr" yaml:"attr"`
	Timestamp string `json:"timestamp" yaml:"timestamp"`
	Digest    string `json:"digest" yaml:"digest"`
}
