// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

import (
	"time"
)

// InstanceSnapshotsPost is generated from api.InstanceSnapshotsPost - DO NOT EDIT!
type InstanceSnapshotsPost struct {
	Name      string     `json:"name" yaml:"name"`
	Stateful  bool       `json:"stateful" yaml:"stateful"`
	ExpiresAt *time.Time `json:"expires_at" yaml:"expires_at"`
}

// InstanceSnapshotPost is generated from api.InstanceSnapshotPost - DO NOT EDIT!
type InstanceSnapshotPost struct {
	Name      string              `json:"name" yaml:"name"`
	Migration bool                `json:"migration" yaml:"migration"`
	Target    *InstancePostTarget `json:"target" yaml:"target"`
	Live      bool                `json:"live,omitempty" yaml:"live,omitempty"`
}

// InstanceSnapshotPut is generated from api.InstanceSnapshotPut - DO NOT EDIT!
type InstanceSnapshotPut struct {
	ExpiresAt time.Time `json:"expires_at" yaml:"expires_at"`
}

// InstanceSnapshot is generated from api.InstanceSnapshot - DO NOT EDIT!
type InstanceSnapshot struct {
	Architecture    string                       `json:"architecture" yaml:"architecture"`
	Config          map[string]string            `json:"config" yaml:"config"`
	CreatedAt       time.Time                    `json:"created_at" yaml:"created_at"`
	ExpiresAt       time.Time                    `json:"expires_at" yaml:"expires_at"`
	Devices         map[string]map[string]string `json:"devices" yaml:"devices"`
	Ephemeral       bool                         `json:"ephemeral" yaml:"ephemeral"`
	ExpandedConfig  map[string]string            `json:"expanded_config,omitempty" yaml:"expanded_config,omitempty"`
	ExpandedDevices map[string]map[string]string `json:"expanded_devices,omitempty" yaml:"expanded_devices,omitempty"`
	LastUsedAt      time.Time                    `json:"last_used_at" yaml:"last_used_at"`
	Name            string                       `json:"name" yaml:"name"`
	Profiles        []string                     `json:"profiles" yaml:"profiles"`
	Stateful        bool                         `json:"stateful" yaml:"stateful"`
	Size            int64                        `json:"size" yaml:"size"`
}

func (c *InstanceSnapshot) Writable() InstanceSnapshotPut {
	return InstanceSnapshotPut{
		ExpiresAt: c.ExpiresAt,
	}
}

func (c *InstanceSnapshot) SetWritable(put InstanceSnapshotPut) {
	c.ExpiresAt = put.ExpiresAt
}
