// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

// MetadataConfiguration is generated from api.MetadataConfiguration - DO NOT EDIT!
type MetadataConfiguration struct {
	Configs  map[string]map[string]MetadataConfigurationConfigKeys `json:"configs" yaml:"configs"`
	Entities map[string]MetadataConfigurationEntity                `json:"entities" yaml:"entities"`
}

// MetadataConfigurationConfigKeys is generated from api.MetadataConfigurationConfigKeys - DO NOT EDIT!
type MetadataConfigurationConfigKeys struct {
	Keys []map[string]MetadataConfigurationConfigKey `json:"keys" yaml:"keys"`
}

// MetadataConfigurationConfigKey is generated from api.MetadataConfigurationConfigKey - DO NOT EDIT!
type MetadataConfigurationConfigKey struct {
	DefaultDescription string `json:"defaultdesc" yaml:"defaultdesc"`
	LongDescription    string `json:"longdesc" yaml:"longdesc"`
	ShortDescription   string `json:"shortdesc" yaml:"shortdesc"`
	Type               string `json:"type" yaml:"type"`
	Condition          string `json:"condition" yaml:"condition"`
	Required           string `json:"required" yaml:"required"`
	Managed            string `json:"managed"`
	Scope              string `json:"scope" yaml:"scope"`
}

// MetadataConfigurationEntity is generated from api.MetadataConfigurationEntity - DO NOT EDIT!
type MetadataConfigurationEntity struct {
	ProjectSpecific bool                                     `json:"project_specific" yaml:"project_specific"`
	Entitlements    []MetadataConfigurationEntityEntitlement `json:"entitlements" yaml:"entitlements"`
}

// MetadataConfigurationEntityEntitlement is generated from api.MetadataConfigurationEntityEntitlement - DO NOT EDIT!
type MetadataConfigurationEntityEntitlement struct {
	Name        string `json:"name" yaml:"name"`
	Description string `json:"description" yaml:"description"`
}
