// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

import (
	"strings"
)

// NetworkACLRule is generated from api.NetworkACLRule - DO NOT EDIT!
type NetworkACLRule struct {
	Action          string `json:"action" yaml:"action"`
	Source          string `json:"source,omitempty" yaml:"source,omitempty"`
	Destination     string `json:"destination,omitempty" yaml:"destination,omitempty"`
	Protocol        string `json:"protocol,omitempty" yaml:"protocol,omitempty"`
	SourcePort      string `json:"source_port,omitempty" yaml:"source_port,omitempty"`
	DestinationPort string `json:"destination_port,omitempty" yaml:"destination_port,omitempty"`
	ICMPType        string `json:"icmp_type,omitempty" yaml:"icmp_type,omitempty"`
	ICMPCode        string `json:"icmp_code,omitempty" yaml:"icmp_code,omitempty"`
	Description     string `json:"description,omitempty" yaml:"description,omitempty"`
	State           string `json:"state" yaml:"state"`
}

func (r *NetworkACLRule) Normalise() {
	r.Action = strings.TrimSpace(r.Action)
	r.Protocol = strings.TrimSpace(r.Protocol)
	r.ICMPType = strings.TrimSpace(r.ICMPType)
	r.ICMPCode = strings.TrimSpace(r.ICMPCode)
	r.Description = strings.TrimSpace(r.Description)
	r.State = strings.TrimSpace(r.State)

	// Remove space from Source subject list.
	subjects := strings.Split(r.Source, ",")
	for i, s := range subjects {
		subjects[i] = strings.TrimSpace(s)
	}

	r.Source = strings.Join(subjects, ",")

	// Remove space from Destination subject list.
	subjects = strings.Split(r.Destination, ",")
	for i, s := range subjects {
		subjects[i] = strings.TrimSpace(s)
	}

	r.Destination = strings.Join(subjects, ",")

	// Remove space from SourcePort port list.
	ports := strings.Split(r.SourcePort, ",")
	for i, s := range ports {
		ports[i] = strings.TrimSpace(s)
	}

	r.SourcePort = strings.Join(ports, ",")

	// Remove space from DestinationPort port list.
	ports = strings.Split(r.DestinationPort, ",")
	for i, s := range ports {
		ports[i] = strings.TrimSpace(s)
	}

	r.DestinationPort = strings.Join(ports, ",")
}

// NetworkACLPost is generated from api.NetworkACLPost - DO NOT EDIT!
type NetworkACLPost struct {
	Name string `json:"name" yaml:"name"`
}

// NetworkACLPut is generated from api.NetworkACLPut - DO NOT EDIT!
type NetworkACLPut struct {
	Description string            `json:"description" yaml:"description"`
	Egress      []NetworkACLRule  `json:"egress" yaml:"egress"`
	Ingress     []NetworkACLRule  `json:"ingress" yaml:"ingress"`
	Config      map[string]string `json:"config" yaml:"config"`
}

// NetworkACL is generated from api.NetworkACL - DO NOT EDIT!
type NetworkACL struct {
	WithEntitlements `yaml:",inline"`
	Name             string            `json:"name" yaml:"name"`
	Description      string            `json:"description" yaml:"description"`
	Egress           []NetworkACLRule  `json:"egress" yaml:"egress"`
	Ingress          []NetworkACLRule  `json:"ingress" yaml:"ingress"`
	Config           map[string]string `json:"config" yaml:"config"`
	UsedBy           []string          `json:"used_by" yaml:"used_by"`
}

func (acl *NetworkACL) Writable() NetworkACLPut {
	return NetworkACLPut{
		Description: acl.Description,
		Ingress:     acl.Ingress,
		Egress:      acl.Egress,
		Config:      acl.Config,
	}
}

func (acl *NetworkACL) SetWritable(put NetworkACLPut) {
	acl.Description = put.Description
	acl.Ingress = put.Ingress
	acl.Egress = put.Egress
	acl.Config = put.Config
}

// NetworkACLsPost is generated from api.NetworkACLsPost - DO NOT EDIT!
type NetworkACLsPost struct {
	NetworkACLPost `yaml:",inline"`
	NetworkACLPut  `yaml:",inline"`
}
