// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

import (
	"net"
	"strings"
)

// NetworkLoadBalancerBackend is generated from api.NetworkLoadBalancerBackend - DO NOT EDIT!
type NetworkLoadBalancerBackend struct {
	Name          string `json:"name" yaml:"name"`
	Description   string `json:"description" yaml:"description"`
	TargetPort    string `json:"target_port" yaml:"target_port"`
	TargetAddress string `json:"target_address" yaml:"target_address"`
}

func (b *NetworkLoadBalancerBackend) Normalise() {
	b.Description = strings.TrimSpace(b.Description)
	b.TargetAddress = strings.TrimSpace(b.TargetAddress)

	ip := net.ParseIP(b.TargetAddress)
	if ip != nil {
		b.TargetAddress = ip.String() // Replace with canonical form if specified.
	}

	// Remove space from TargetPort list.
	subjects := strings.Split(b.TargetPort, ",")
	for i, s := range subjects {
		subjects[i] = strings.TrimSpace(s)
	}

	b.TargetPort = strings.Join(subjects, ",")
}

// NetworkLoadBalancerPort is generated from api.NetworkLoadBalancerPort - DO NOT EDIT!
type NetworkLoadBalancerPort struct {
	Description   string   `json:"description" yaml:"description"`
	Protocol      string   `json:"protocol" yaml:"protocol"`
	ListenPort    string   `json:"listen_port" yaml:"listen_port"`
	TargetBackend []string `json:"target_backend" yaml:"target_backend"`
}

func (p *NetworkLoadBalancerPort) Normalise() {
	p.Description = strings.TrimSpace(p.Description)
	p.Protocol = strings.TrimSpace(p.Protocol)

	// Remove space from ListenPort list.
	subjects := strings.Split(p.ListenPort, ",")
	for i, s := range subjects {
		subjects[i] = strings.TrimSpace(s)
	}

	p.ListenPort = strings.Join(subjects, ",")
}

// NetworkLoadBalancersPost is generated from api.NetworkLoadBalancersPost - DO NOT EDIT!
type NetworkLoadBalancersPost struct {
	NetworkLoadBalancerPut `yaml:",inline"`
	ListenAddress          string `json:"listen_address" yaml:"listen_address"`
}

// NetworkLoadBalancerPut is generated from api.NetworkLoadBalancerPut - DO NOT EDIT!
type NetworkLoadBalancerPut struct {
	Description string                       `json:"description" yaml:"description"`
	Config      map[string]string            `json:"config" yaml:"config"`
	Backends    []NetworkLoadBalancerBackend `json:"backends" yaml:"backends"`
	Ports       []NetworkLoadBalancerPort    `json:"ports" yaml:"ports"`
}

func (f *NetworkLoadBalancerPut) Normalise() {
	f.Description = strings.TrimSpace(f.Description)

	for i := range f.Backends {
		f.Backends[i].Normalise()
	}

	for i := range f.Ports {
		f.Ports[i].Normalise()
	}
}

// NetworkLoadBalancer is generated from api.NetworkLoadBalancer - DO NOT EDIT!
type NetworkLoadBalancer struct {
	ListenAddress string                       `json:"listen_address" yaml:"listen_address"`
	Location      string                       `json:"location" yaml:"location"`
	Description   string                       `json:"description" yaml:"description"`
	Config        map[string]string            `json:"config" yaml:"config"`
	Backends      []NetworkLoadBalancerBackend `json:"backends" yaml:"backends"`
	Ports         []NetworkLoadBalancerPort    `json:"ports" yaml:"ports"`
}

func (lb *NetworkLoadBalancer) Normalise() {
	lbPut := lb.Writable()
	lbPut.Normalise()
	lb.SetWritable(lbPut)
}

func (lb *NetworkLoadBalancer) Etag() []any {
	return []any{lb.ListenAddress, lb.Description, lb.Config, lb.Backends, lb.Ports}
}

func (lb *NetworkLoadBalancer) Writable() NetworkLoadBalancerPut {
	return NetworkLoadBalancerPut{
		Description: lb.Description,
		Config:      lb.Config,
		Backends:    lb.Backends,
		Ports:       lb.Ports,
	}
}

func (lb *NetworkLoadBalancer) SetWritable(put NetworkLoadBalancerPut) {
	lb.Description = put.Description
	lb.Config = put.Config
	lb.Backends = put.Backends
	lb.Ports = put.Ports
}
