// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

import (
	"net"
	"strings"
)

// NetworkForwardPort is generated from api.NetworkForwardPort - DO NOT EDIT!
type NetworkForwardPort struct {
	Description   string `json:"description" yaml:"description"`
	Protocol      string `json:"protocol" yaml:"protocol"`
	ListenPort    string `json:"listen_port" yaml:"listen_port"`
	TargetPort    string `json:"target_port" yaml:"target_port"`
	TargetAddress string `json:"target_address" yaml:"target_address"`
}

func (p *NetworkForwardPort) Normalise() {
	p.Description = strings.TrimSpace(p.Description)
	p.Protocol = strings.TrimSpace(p.Protocol)
	p.TargetAddress = strings.TrimSpace(p.TargetAddress)

	ip := net.ParseIP(p.TargetAddress)
	if ip != nil {
		p.TargetAddress = ip.String() // Replace with canonical form if specified.
	}

	// Remove space from ListenPort list.
	subjects := strings.Split(p.ListenPort, ",")
	for i, s := range subjects {
		subjects[i] = strings.TrimSpace(s)
	}

	p.ListenPort = strings.Join(subjects, ",")

	// Remove space from TargetPort list.
	subjects = strings.Split(p.TargetPort, ",")
	for i, s := range subjects {
		subjects[i] = strings.TrimSpace(s)
	}

	p.TargetPort = strings.Join(subjects, ",")
}

// NetworkForwardsPost is generated from api.NetworkForwardsPost - DO NOT EDIT!
type NetworkForwardsPost struct {
	NetworkForwardPut `yaml:",inline"`
	ListenAddress     string `json:"listen_address" yaml:"listen_address"`
}

func (f *NetworkForwardsPost) Normalise() {
	ip := net.ParseIP(f.ListenAddress)
	if ip != nil {
		f.ListenAddress = ip.String() // Replace with canonical form if specified.
	}

	f.NetworkForwardPut.Normalise()
}

// NetworkForwardPut is generated from api.NetworkForwardPut - DO NOT EDIT!
type NetworkForwardPut struct {
	Description string               `json:"description" yaml:"description"`
	Config      map[string]string    `json:"config" yaml:"config"`
	Ports       []NetworkForwardPort `json:"ports" yaml:"ports"`
}

func (f *NetworkForwardPut) Normalise() {
	f.Description = strings.TrimSpace(f.Description)

	ip := net.ParseIP(f.Config["target_address"])
	if ip != nil {
		f.Config["target_address"] = ip.String() // Replace with canonical form if specified.
	}

	for i := range f.Ports {
		f.Ports[i].Normalise()
	}
}

// NetworkForward is generated from api.NetworkForward - DO NOT EDIT!
type NetworkForward struct {
	ListenAddress string               `json:"listen_address" yaml:"listen_address"`
	Location      string               `json:"location" yaml:"location"`
	Description   string               `json:"description" yaml:"description"`
	Config        map[string]string    `json:"config" yaml:"config"`
	Ports         []NetworkForwardPort `json:"ports" yaml:"ports"`
}

func (f *NetworkForward) Normalise() {
	fPut := f.Writable()
	fPut.Normalise()
	f.SetWritable(fPut)
}

func (f *NetworkForward) Etag() []any {
	return []any{f.ListenAddress, f.Description, f.Config, f.Ports}
}

func (f *NetworkForward) Writable() NetworkForwardPut {
	return NetworkForwardPut{
		Description: f.Description,
		Config:      f.Config,
		Ports:       f.Ports,
	}
}

func (f *NetworkForward) SetWritable(put NetworkForwardPut) {
	f.Description = put.Description
	f.Config = put.Config
	f.Ports = put.Ports
}
