// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

// NetworkPeersPost is generated from api.NetworkPeersPost - DO NOT EDIT!
type NetworkPeersPost struct {
	NetworkPeerPut `yaml:",inline"`
	Name           string `json:"name" yaml:"name"`
	TargetProject  string `json:"target_project" yaml:"target_project"`
	TargetNetwork  string `json:"target_network" yaml:"target_network"`
}

// NetworkPeerPut is generated from api.NetworkPeerPut - DO NOT EDIT!
type NetworkPeerPut struct {
	Description string            `json:"description" yaml:"description"`
	Config      map[string]string `json:"config" yaml:"config"`
}

// NetworkPeer is generated from api.NetworkPeer - DO NOT EDIT!
type NetworkPeer struct {
	Name          string            `json:"name" yaml:"name"`
	Description   string            `json:"description" yaml:"description"`
	TargetProject string            `json:"target_project" yaml:"target_project"`
	TargetNetwork string            `json:"target_network" yaml:"target_network"`
	Status        string            `json:"status" yaml:"status"`
	Config        map[string]string `json:"config" yaml:"config"`
	UsedBy        []string          `json:"used_by" yaml:"used_by"`
}

func (p *NetworkPeer) Etag() []any {
	return []any{p.Name, p.Description, p.Config}
}

func (p *NetworkPeer) Writable() NetworkPeerPut {
	return NetworkPeerPut{
		Description: p.Description,
		Config:      p.Config,
	}
}

func (p *NetworkPeer) SetWritable(put NetworkPeerPut) {
	p.Description = put.Description
	p.Config = put.Config
}
