// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

// NetworkZonesPost is generated from api.NetworkZonesPost - DO NOT EDIT!
type NetworkZonesPost struct {
	NetworkZonePut `yaml:",inline"`
	Name           string `json:"name" yaml:"name"`
}

// NetworkZonePut is generated from api.NetworkZonePut - DO NOT EDIT!
type NetworkZonePut struct {
	Description string            `json:"description" yaml:"description"`
	Config      map[string]string `json:"config" yaml:"config"`
}

// NetworkZone is generated from api.NetworkZone - DO NOT EDIT!
type NetworkZone struct {
	WithEntitlements `yaml:",inline"`
	Name             string            `json:"name" yaml:"name"`
	Description      string            `json:"description" yaml:"description"`
	Config           map[string]string `json:"config" yaml:"config"`
	UsedBy           []string          `json:"used_by" yaml:"used_by"`
	Project          string            `json:"project" yaml:"project"`
}

func (zone *NetworkZone) Writable() NetworkZonePut {
	return NetworkZonePut{
		Description: zone.Description,
		Config:      zone.Config,
	}
}

func (zone *NetworkZone) SetWritable(put NetworkZonePut) {
	zone.Description = put.Description
	zone.Config = put.Config
}

// NetworkZoneRecordsPost is generated from api.NetworkZoneRecordsPost - DO NOT EDIT!
type NetworkZoneRecordsPost struct {
	NetworkZoneRecordPut `yaml:",inline"`
	Name                 string `json:"name" yaml:"name"`
}

// NetworkZoneRecordPut is generated from api.NetworkZoneRecordPut - DO NOT EDIT!
type NetworkZoneRecordPut struct {
	Description string                   `json:"description" yaml:"description"`
	Entries     []NetworkZoneRecordEntry `json:"entries" yaml:"entries"`
	Config      map[string]string        `json:"config" yaml:"config"`
}

// NetworkZoneRecordEntry is generated from api.NetworkZoneRecordEntry - DO NOT EDIT!
type NetworkZoneRecordEntry struct {
	Type  string `json:"type" yaml:"type"`
	TTL   uint64 `json:"ttl,omitempty" yaml:"ttl,omitempty"`
	Value string `json:"value" yaml:"value"`
}

// NetworkZoneRecord is generated from api.NetworkZoneRecord - DO NOT EDIT!
type NetworkZoneRecord struct {
	Name        string                   `json:"name" yaml:"name"`
	Description string                   `json:"description" yaml:"description"`
	Entries     []NetworkZoneRecordEntry `json:"entries" yaml:"entries"`
	Config      map[string]string        `json:"config" yaml:"config"`
}

func (record *NetworkZoneRecord) Writable() NetworkZoneRecordPut {
	return NetworkZoneRecordPut{
		Description: record.Description,
		Entries:     record.Entries,
		Config:      record.Config,
	}
}

func (record *NetworkZoneRecord) SetWritable(put NetworkZoneRecordPut) {
	record.Description = put.Description
	record.Config = put.Config
	record.Entries = put.Entries
}
