// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

// NetworksPost is generated from api.NetworksPost - DO NOT EDIT!
type NetworksPost struct {
	NetworkPut `yaml:",inline"`
	Name       string `json:"name" yaml:"name"`
	Type       string `json:"type" yaml:"type"`
}

// NetworkPost is generated from api.NetworkPost - DO NOT EDIT!
type NetworkPost struct {
	Name string `json:"name" yaml:"name"`
}

// NetworkPut is generated from api.NetworkPut - DO NOT EDIT!
type NetworkPut struct {
	Config      map[string]string `json:"config" yaml:"config"`
	Description string            `json:"description" yaml:"description"`
}

// Network is generated from api.Network - DO NOT EDIT!
type Network struct {
	WithEntitlements `yaml:",inline"`
	Name             string            `json:"name" yaml:"name"`
	Description      string            `json:"description" yaml:"description"`
	Type             string            `json:"type" yaml:"type"`
	Managed          bool              `json:"managed" yaml:"managed"`
	Status           string            `json:"status" yaml:"status"`
	Config           map[string]string `json:"config" yaml:"config"`
	UsedBy           []string          `json:"used_by" yaml:"used_by"`
	Locations        []string          `json:"locations" yaml:"locations"`
}

func (network *Network) Writable() NetworkPut {
	return NetworkPut{
		Description: network.Description,
		Config:      network.Config,
	}
}

func (network *Network) SetWritable(put NetworkPut) {
	network.Description = put.Description
	network.Config = put.Config
}

// NetworkLease is generated from api.NetworkLease - DO NOT EDIT!
type NetworkLease struct {
	Hostname string `json:"hostname" yaml:"hostname"`
	Hwaddr   string `json:"hwaddr" yaml:"hwaddr"`
	Address  string `json:"address" yaml:"address"`
	Type     string `json:"type" yaml:"type"`
	Location string `json:"location" yaml:"location"`
	Project  string `json:"project" yaml:"project"`
}

// NetworkState is generated from api.NetworkState - DO NOT EDIT!
type NetworkState struct {
	Addresses []NetworkStateAddress `json:"addresses" yaml:"addresses"`
	Counters  NetworkStateCounters  `json:"counters" yaml:"counters"`
	Hwaddr    string                `json:"hwaddr" yaml:"hwaddr"`
	Mtu       int                   `json:"mtu" yaml:"mtu"`
	State     string                `json:"state" yaml:"state"`
	Type      string                `json:"type" yaml:"type"`
	Bond      *NetworkStateBond     `json:"bond" yaml:"bond"`
	Bridge    *NetworkStateBridge   `json:"bridge" yaml:"bridge"`
	VLAN      *NetworkStateVLAN     `json:"vlan" yaml:"vlan"`
	OVN       *NetworkStateOVN      `json:"ovn" yaml:"ovn"`
}

// NetworkStateAddress is generated from api.NetworkStateAddress - DO NOT EDIT!
type NetworkStateAddress struct {
	Family  string `json:"family" yaml:"family"`
	Address string `json:"address" yaml:"address"`
	Netmask string `json:"netmask" yaml:"netmask"`
	Scope   string `json:"scope" yaml:"scope"`
}

// NetworkStateCounters is generated from api.NetworkStateCounters - DO NOT EDIT!
type NetworkStateCounters struct {
	BytesReceived   int64 `json:"bytes_received" yaml:"bytes_received"`
	BytesSent       int64 `json:"bytes_sent" yaml:"bytes_sent"`
	PacketsReceived int64 `json:"packets_received" yaml:"packets_received"`
	PacketsSent     int64 `json:"packets_sent" yaml:"packets_sent"`
}

// NetworkStateBond is generated from api.NetworkStateBond - DO NOT EDIT!
type NetworkStateBond struct {
	Mode           string   `json:"mode" yaml:"mode"`
	TransmitPolicy string   `json:"transmit_policy" yaml:"transmit_policy"`
	UpDelay        uint64   `json:"up_delay" yaml:"up_delay"`
	DownDelay      uint64   `json:"down_delay" yaml:"down_delay"`
	MIIFrequency   uint64   `json:"mii_frequency" yaml:"mii_frequency"`
	MIIState       string   `json:"mii_state" yaml:"mii_state"`
	LowerDevices   []string `json:"lower_devices" yaml:"lower_devices"`
}

// NetworkStateBridge is generated from api.NetworkStateBridge - DO NOT EDIT!
type NetworkStateBridge struct {
	ID            string   `json:"id" yaml:"id"`
	STP           bool     `json:"stp" yaml:"stp"`
	ForwardDelay  uint64   `json:"forward_delay" yaml:"forward_delay"`
	VLANDefault   uint64   `json:"vlan_default" yaml:"vlan_default"`
	VLANFiltering bool     `json:"vlan_filtering" yaml:"vlan_filtering"`
	UpperDevices  []string `json:"upper_devices" yaml:"upper_devices"`
}

// NetworkStateVLAN is generated from api.NetworkStateVLAN - DO NOT EDIT!
type NetworkStateVLAN struct {
	LowerDevice string `json:"lower_device" yaml:"lower_device"`
	VID         uint64 `json:"vid" yaml:"vid"`
}

// NetworkStateOVN is generated from api.NetworkStateOVN - DO NOT EDIT!
type NetworkStateOVN struct {
	Chassis string `json:"chassis" yaml:"chassis"`
}
