// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

// NetworkAllocations is generated from api.NetworkAllocations - DO NOT EDIT!
type NetworkAllocations struct {
	Address string `json:"addresses" yaml:"addresses"`
	UsedBy  string `json:"used_by" yaml:"used_by"`
	Type    string `json:"type" yaml:"type"`
	NAT     bool   `json:"nat" yaml:"nat"`
	Hwaddr  string `json:"hwaddr" yaml:"hwaddr"`
	Network string `json:"network" yaml:"network"`
}
