// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

// ProfilesPost is generated from api.ProfilesPost - DO NOT EDIT!
type ProfilesPost struct {
	ProfilePut `yaml:",inline"`
	Name       string `json:"name" yaml:"name" db:"primary=yes"`
}

// ProfilePost is generated from api.ProfilePost - DO NOT EDIT!
type ProfilePost struct {
	Name string `json:"name" yaml:"name"`
}

// ProfilePut is generated from api.ProfilePut - DO NOT EDIT!
type ProfilePut struct {
	Config      map[string]string            `json:"config" yaml:"config"`
	Description string                       `json:"description" yaml:"description"`
	Devices     map[string]map[string]string `json:"devices" yaml:"devices"`
}

// Profile is generated from api.Profile - DO NOT EDIT!
type Profile struct {
	WithEntitlements `yaml:",inline"`
	Name             string                       `json:"name" yaml:"name" db:"primary=yes"`
	Description      string                       `json:"description" yaml:"description"`
	Config           map[string]string            `json:"config" yaml:"config"`
	Devices          map[string]map[string]string `json:"devices" yaml:"devices"`
	UsedBy           []string                     `json:"used_by" yaml:"used_by"`
	Project          string                       `json:"project" yaml:"project"`
}

func (profile *Profile) Writable() ProfilePut {
	return ProfilePut{
		Description: profile.Description,
		Config:      profile.Config,
		Devices:     profile.Devices,
	}
}

func (profile *Profile) SetWritable(put ProfilePut) {
	profile.Description = put.Description
	profile.Config = put.Config
	profile.Devices = put.Devices
}
