// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

// ProjectsPost is generated from api.ProjectsPost - DO NOT EDIT!
type ProjectsPost struct {
	ProjectPut  `yaml:",inline"`
	Name        string `json:"name" yaml:"name"`
	StoragePool string `json:"storage" yaml:"storage"`
	Network     string `json:"network" yaml:"network"`
}

// ProjectPost is generated from api.ProjectPost - DO NOT EDIT!
type ProjectPost struct {
	Name string `json:"name" yaml:"name"`
}

// ProjectPut is generated from api.ProjectPut - DO NOT EDIT!
type ProjectPut struct {
	Config      map[string]string `json:"config" yaml:"config"`
	Description string            `json:"description" yaml:"description"`
}

// Project is generated from api.Project - DO NOT EDIT!
type Project struct {
	WithEntitlements `yaml:",inline"`
	Name             string            `json:"name" yaml:"name"`
	Description      string            `json:"description" yaml:"description"`
	Config           map[string]string `json:"config" yaml:"config"`
	UsedBy           []string          `json:"used_by" yaml:"used_by"`
}

func (project *Project) Writable() ProjectPut {
	return ProjectPut{
		Description: project.Description,
		Config:      project.Config,
	}
}

func (project *Project) SetWritable(put ProjectPut) {
	project.Description = put.Description
	project.Config = put.Config
}

// ProjectState is generated from api.ProjectState - DO NOT EDIT!
type ProjectState struct {
	Resources map[string]ProjectStateResource `json:"resources" yaml:"resources"`
}

// ProjectStateResource is generated from api.ProjectStateResource - DO NOT EDIT!
type ProjectStateResource struct {
	Limit int64
	Usage int64
}
