// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

import (
	"encoding/json"

	"github.com/canonical/lxd/shared/api"
)

// ResponseRaw is generated from api.ResponseRaw - DO NOT EDIT!
type ResponseRaw struct {
	Type       api.ResponseType `json:"type" yaml:"type" shadow:"response_type"`
	Status     string           `json:"status" yaml:"status"`
	StatusCode int              `json:"status_code" yaml:"status_code"`
	Operation  string           `json:"operation" yaml:"operation"`
	Code       int              `json:"error_code" yaml:"error_code"`
	Error      string           `json:"error" yaml:"error"`
	Metadata   any              `json:"metadata" yaml:"metadata"`
}

// Response is generated from api.Response - DO NOT EDIT!
type Response struct {
	Type       api.ResponseType `json:"type" yaml:"type" shadow:"response_type"`
	Status     string           `json:"status" yaml:"status"`
	StatusCode int              `json:"status_code" yaml:"status_code"`
	Operation  string           `json:"operation" yaml:"operation"`
	Code       int              `json:"error_code" yaml:"error_code"`
	Error      string           `json:"error" yaml:"error"`
	Metadata   json.RawMessage  `json:"metadata" yaml:"metadata"`
}

func (r *Response) MetadataAsMap() (map[string]any, error) {
	ret := map[string]any{}
	err := r.MetadataAsStruct(&ret)
	if err != nil {
		return nil, err
	}

	return ret, nil
}

func (r *Response) MetadataAsOperation() (*Operation, error) {
	op := Operation{}
	err := r.MetadataAsStruct(&op)
	if err != nil {
		return nil, err
	}

	return &op, nil
}

func (r *Response) MetadataAsStringSlice() ([]string, error) {
	sl := []string{}
	err := r.MetadataAsStruct(&sl)
	if err != nil {
		return nil, err
	}

	return sl, nil
}

func (r *Response) MetadataAsStruct(target any) error {
	return json.Unmarshal(r.Metadata, &target)
}
