// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

// ServerEnvironment is generated from api.ServerEnvironment - DO NOT EDIT!
type ServerEnvironment struct {
	Addresses               []string                  `json:"addresses" yaml:"addresses"`
	Architectures           []string                  `json:"architectures" yaml:"architectures"`
	Certificate             string                    `json:"certificate" yaml:"certificate"`
	CertificateFingerprint  string                    `json:"certificate_fingerprint" yaml:"certificate_fingerprint"`
	Driver                  string                    `json:"driver" yaml:"driver"`
	DriverVersion           string                    `json:"driver_version" yaml:"driver_version"`
	InstanceTypes           []string                  `json:"instance_types" yaml:"instance_types"`
	Firewall                string                    `json:"firewall" yaml:"firewall"`
	Kernel                  string                    `json:"kernel" yaml:"kernel"`
	KernelArchitecture      string                    `json:"kernel_architecture" yaml:"kernel_architecture"`
	KernelFeatures          map[string]string         `json:"kernel_features" yaml:"kernel_features"`
	KernelVersion           string                    `json:"kernel_version" yaml:"kernel_version"`
	LXCFeatures             map[string]string         `json:"lxc_features" yaml:"lxc_features"`
	OSName                  string                    `json:"os_name" yaml:"os_name"`
	OSVersion               string                    `json:"os_version" yaml:"os_version"`
	Project                 string                    `json:"project" yaml:"project"`
	Server                  string                    `json:"server" yaml:"server"`
	ServerClustered         bool                      `json:"server_clustered" yaml:"server_clustered"`
	ServerEventMode         string                    `json:"server_event_mode" yaml:"server_event_mode"`
	ServerName              string                    `json:"server_name" yaml:"server_name"`
	ServerPid               int                       `json:"server_pid" yaml:"server_pid"`
	ServerVersion           string                    `json:"server_version" yaml:"server_version"`
	ServerLTS               bool                      `json:"server_lts" yaml:"server_lts"`
	Storage                 string                    `json:"storage" yaml:"storage"`
	StorageVersion          string                    `json:"storage_version" yaml:"storage_version"`
	StorageSupportedDrivers []ServerStorageDriverInfo `json:"storage_supported_drivers" yaml:"storage_supported_drivers"`
}

// ServerStorageDriverInfo is generated from api.ServerStorageDriverInfo - DO NOT EDIT!
type ServerStorageDriverInfo struct {
	Name    string
	Version string
	Remote  bool
}

// ServerPut is generated from api.ServerPut - DO NOT EDIT!
type ServerPut struct {
	Config map[string]any `json:"config" yaml:"config"`
}

// ServerUntrusted is generated from api.ServerUntrusted - DO NOT EDIT!
type ServerUntrusted struct {
	APIExtensions []string `json:"api_extensions" yaml:"api_extensions"`
	APIStatus     string   `json:"api_status" yaml:"api_status"`
	APIVersion    string   `json:"api_version" yaml:"api_version"`
	Auth          string   `json:"auth" yaml:"auth"`
	Public        bool     `json:"public" yaml:"public"`
	AuthMethods   []string `json:"auth_methods" yaml:"auth_methods"`
}

// Server is generated from api.Server - DO NOT EDIT!
type Server struct {
	WithEntitlements `yaml:",inline"`
	ServerPut        `yaml:",inline"`
	ServerUntrusted  `yaml:",inline"`
	AuthUserName     string            `json:"auth_user_name" yaml:"auth_user_name"`
	AuthUserMethod   string            `json:"auth_user_method" yaml:"auth_user_method"`
	Environment      ServerEnvironment `json:"environment" yaml:"environment"`
}

func (srv *Server) Writable() ServerPut {
	return srv.ServerPut
}
