// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

// StoragePoolsPost is generated from api.StoragePoolsPost - DO NOT EDIT!
type StoragePoolsPost struct {
	StoragePoolPut `yaml:",inline"`
	Name           string `json:"name" yaml:"name"`
	Driver         string `json:"driver" yaml:"driver"`
}

// StoragePool is generated from api.StoragePool - DO NOT EDIT!
type StoragePool struct {
	WithEntitlements `yaml:",inline"`
	Name             string            `json:"name" yaml:"name"`
	Description      string            `json:"description" yaml:"description"`
	Driver           string            `json:"driver" yaml:"driver"`
	Status           string            `json:"status" yaml:"status"`
	Config           map[string]string `json:"config" yaml:"config"`
	UsedBy           []string          `json:"used_by" yaml:"used_by"`
	Locations        []string          `json:"locations" yaml:"locations"`
}

// StoragePoolPut is generated from api.StoragePoolPut - DO NOT EDIT!
type StoragePoolPut struct {
	Config      map[string]string `json:"config" yaml:"config"`
	Description string            `json:"description" yaml:"description"`
}

func (storagePool *StoragePool) Writable() StoragePoolPut {
	return StoragePoolPut{
		Description: storagePool.Description,
		Config:      storagePool.Config,
	}
}

func (storagePool *StoragePool) SetWritable(put StoragePoolPut) {
	storagePool.Description = put.Description
	storagePool.Config = put.Config
}

// StoragePoolState is generated from api.StoragePoolState - DO NOT EDIT!
type StoragePoolState struct {
	ResourcesStoragePool `yaml:",inline"`
}
