// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

import (
	"time"
)

// StoragePoolVolumeBackup is generated from api.StoragePoolVolumeBackup - DO NOT EDIT!
type StoragePoolVolumeBackup struct {
	Name             string    `json:"name" yaml:"name"`
	CreatedAt        time.Time `json:"created_at" yaml:"created_at"`
	ExpiresAt        time.Time `json:"expires_at" yaml:"expires_at"`
	VolumeOnly       bool      `json:"volume_only" yaml:"volume_only"`
	OptimizedStorage bool      `json:"optimized_storage" yaml:"optimized_storage"`
}

// StoragePoolVolumeBackupsPost is generated from api.StoragePoolVolumeBackupsPost - DO NOT EDIT!
type StoragePoolVolumeBackupsPost struct {
	Name                 string    `json:"name" yaml:"name"`
	ExpiresAt            time.Time `json:"expires_at" yaml:"expires_at"`
	VolumeOnly           bool      `json:"volume_only" yaml:"volume_only"`
	OptimizedStorage     bool      `json:"optimized_storage" yaml:"optimized_storage"`
	CompressionAlgorithm string    `json:"compression_algorithm" yaml:"compression_algorithm"`
}

// StoragePoolVolumeBackupPost is generated from api.StoragePoolVolumeBackupPost - DO NOT EDIT!
type StoragePoolVolumeBackupPost struct {
	Name string `json:"name" yaml:"name"`
}
