// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

import (
	"time"
)

// StorageVolumesPost is generated from api.StorageVolumesPost - DO NOT EDIT!
type StorageVolumesPost struct {
	StorageVolumePut `yaml:",inline"`
	Name             string              `json:"name" yaml:"name"`
	Type             string              `json:"type" yaml:"type"`
	Source           StorageVolumeSource `json:"source" yaml:"source"`
	ContentType      string              `json:"content_type" yaml:"content_type"`
}

// StorageVolumePost is generated from api.StorageVolumePost - DO NOT EDIT!
type StorageVolumePost struct {
	Name       string                   `json:"name" yaml:"name"`
	Pool       string                   `json:"pool,omitempty" yaml:"pool,omitempty"`
	Migration  bool                     `json:"migration" yaml:"migration"`
	Target     *StorageVolumePostTarget `json:"target" yaml:"target"`
	VolumeOnly bool                     `json:"volume_only" yaml:"volume_only"`
	Project    string                   `json:"project,omitempty" yaml:"project,omitempty"`
	Source     StorageVolumeSource      `json:"source" yaml:"source"`
}

// StorageVolumePostTarget is generated from api.StorageVolumePostTarget - DO NOT EDIT!
type StorageVolumePostTarget struct {
	Certificate string            `json:"certificate" yaml:"certificate"`
	Operation   string            `json:"operation,omitempty" yaml:"operation,omitempty"`
	Websockets  map[string]string `json:"secrets,omitempty" yaml:"secrets,omitempty"`
}

// StorageVolume is generated from api.StorageVolume - DO NOT EDIT!
type StorageVolume struct {
	WithEntitlements `yaml:",inline"`
	Name             string            `json:"name" yaml:"name"`
	Description      string            `json:"description" yaml:"description"`
	Type             string            `json:"type" yaml:"type"`
	Pool             string            `json:"pool" yaml:"pool"`
	ContentType      string            `json:"content_type" yaml:"content_type"`
	Project          string            `json:"project" yaml:"project"`
	Location         string            `json:"location" yaml:"location"`
	CreatedAt        time.Time         `json:"created_at" yaml:"created_at"`
	Config           map[string]string `json:"config" yaml:"config"`
	UsedBy           []string          `json:"used_by" yaml:"used_by"`
}

// StorageVolumePut is generated from api.StorageVolumePut - DO NOT EDIT!
type StorageVolumePut struct {
	Config      map[string]string `json:"config" yaml:"config"`
	Description string            `json:"description" yaml:"description"`
	Restore     string            `json:"restore,omitempty" yaml:"restore,omitempty"`
}

// StorageVolumeSource is generated from api.StorageVolumeSource - DO NOT EDIT!
type StorageVolumeSource struct {
	Name        string            `json:"name" yaml:"name"`
	Type        string            `json:"type" yaml:"type"`
	Pool        string            `json:"pool" yaml:"pool"`
	Certificate string            `json:"certificate" yaml:"certificate"`
	Mode        string            `json:"mode,omitempty" yaml:"mode,omitempty"`
	Operation   string            `json:"operation,omitempty" yaml:"operation,omitempty"`
	Websockets  map[string]string `json:"secrets,omitempty" yaml:"secrets,omitempty"`
	VolumeOnly  bool              `json:"volume_only" yaml:"volume_only"`
	Refresh     bool              `json:"refresh" yaml:"refresh"`
	Project     string            `json:"project,omitempty" yaml:"project,omitempty"`
	Location    string            `json:"location" yaml:"location"`
}

func (v *StorageVolume) Writable() StorageVolumePut {
	return StorageVolumePut{
		Description: v.Description,
		Config:      v.Config,
	}
}

func (v *StorageVolume) SetWritable(put StorageVolumePut) {
	v.Description = put.Description
	v.Config = put.Config
}
