// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

// StorageVolumeState is generated from api.StorageVolumeState - DO NOT EDIT!
type StorageVolumeState struct {
	Usage *StorageVolumeStateUsage `json:"usage" yaml:"usage"`
}

// StorageVolumeStateUsage is generated from api.StorageVolumeStateUsage - DO NOT EDIT!
type StorageVolumeStateUsage struct {
	Used  uint64 `json:"used" yaml:"used"`
	Total int64  `json:"total" yaml:"total"`
}
