// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

import (
	"time"
)

// StorageVolumeSnapshotsPost is generated from api.StorageVolumeSnapshotsPost - DO NOT EDIT!
type StorageVolumeSnapshotsPost struct {
	Name        string     `json:"name" yaml:"name"`
	Description string     `json:"description" yaml:"description"`
	ExpiresAt   *time.Time `json:"expires_at" yaml:"expires_at"`
}

// StorageVolumeSnapshotPost is generated from api.StorageVolumeSnapshotPost - DO NOT EDIT!
type StorageVolumeSnapshotPost struct {
	Name      string                   `json:"name" yaml:"name"`
	Migration bool                     `json:"migration" yaml:"migration"`
	Target    *StorageVolumePostTarget `json:"target" yaml:"target"`
}

// StorageVolumeSnapshot is generated from api.StorageVolumeSnapshot - DO NOT EDIT!
type StorageVolumeSnapshot struct {
	Name        string            `json:"name" yaml:"name"`
	Description string            `json:"description" yaml:"description"`
	ContentType string            `json:"content_type" yaml:"content_type"`
	CreatedAt   time.Time         `json:"created_at" yaml:"created_at"`
	ExpiresAt   *time.Time        `json:"expires_at" yaml:"expires_at"`
	Config      map[string]string `json:"config" yaml:"config"`
}

// StorageVolumeSnapshotPut is generated from api.StorageVolumeSnapshotPut - DO NOT EDIT!
type StorageVolumeSnapshotPut struct {
	Description string     `json:"description" yaml:"description"`
	ExpiresAt   *time.Time `json:"expires_at" yaml:"expires_at"`
}

func (storageVolumeSnapshot *StorageVolumeSnapshot) Writable() StorageVolumeSnapshotPut {
	return StorageVolumeSnapshotPut{
		Description: storageVolumeSnapshot.Description,
		ExpiresAt:   storageVolumeSnapshot.ExpiresAt,
	}
}

func (storageVolumeSnapshot *StorageVolumeSnapshot) SetWritable(put StorageVolumeSnapshotPut) {
	storageVolumeSnapshot.Description = put.Description
	storageVolumeSnapshot.ExpiresAt = put.ExpiresAt
}
