// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

// StorageBucketsPost is generated from api.StorageBucketsPost - DO NOT EDIT!
type StorageBucketsPost struct {
	StorageBucketPut `yaml:",inline"`
	Name             string `json:"name" yaml:"name"`
}

// StorageBucketPut is generated from api.StorageBucketPut - DO NOT EDIT!
type StorageBucketPut struct {
	Config      map[string]string `json:"config" yaml:"config"`
	Description string            `json:"description" yaml:"description"`
}

// StorageBucket is generated from api.StorageBucket - DO NOT EDIT!
type StorageBucket struct {
	WithEntitlements `yaml:",inline"`
	Name             string            `json:"name" yaml:"name"`
	Description      string            `json:"description" yaml:"description"`
	S3URL            string            `json:"s3_url" yaml:"s3_url"`
	Location         string            `json:"location" yaml:"location"`
	Config           map[string]string `json:"config" yaml:"config"`
}

func (b *StorageBucket) Etag() []any {
	return []any{b.Name, b.Description, b.Config}
}

func (b *StorageBucket) Writable() StorageBucketPut {
	return StorageBucketPut{
		Description: b.Description,
		Config:      b.Config,
	}
}

func (b *StorageBucket) SetWritable(put StorageBucketPut) {
	b.Description = put.Description
	b.Config = put.Config
}

// StorageBucketKeysPost is generated from api.StorageBucketKeysPost - DO NOT EDIT!
type StorageBucketKeysPost struct {
	StorageBucketKeyPut `yaml:",inline"`
	Name                string `json:"name" yaml:"name"`
}

// StorageBucketKeyPut is generated from api.StorageBucketKeyPut - DO NOT EDIT!
type StorageBucketKeyPut struct {
	Description string `json:"description" yaml:"description"`
	Role        string `json:"role" yaml:"role"`
	AccessKey   string `json:"access-key" yaml:"access-key"`
	SecretKey   string `json:"secret-key" yaml:"secret-key"`
}

// StorageBucketKey is generated from api.StorageBucketKey - DO NOT EDIT!
type StorageBucketKey struct {
	Name        string `json:"name" yaml:"name"`
	Description string `json:"description" yaml:"description"`
	Role        string `json:"role" yaml:"role"`
	AccessKey   string `json:"access-key" yaml:"access-key"`
	SecretKey   string `json:"secret-key" yaml:"secret-key"`
}

func (b *StorageBucketKey) Etag() []any {
	return []any{b.Name, b.Description, b.Role, b.AccessKey, b.SecretKey}
}

func (b *StorageBucketKey) Writable() StorageBucketKeyPut {
	return StorageBucketKeyPut{
		Description: b.Description,
		Role:        b.Role,
		AccessKey:   b.AccessKey,
		SecretKey:   b.SecretKey,
	}
}

func (b *StorageBucketKey) SetWritable(put StorageBucketKeyPut) {
	b.Description = put.Description
	b.Role = put.Role
	b.AccessKey = put.AccessKey
	b.SecretKey = put.SecretKey
}
