// Code generated by shadowapi/generate - DO NOT EDIT!

package shadowapi

import (
	"time"
)

// Warning is generated from api.Warning - DO NOT EDIT!
type Warning struct {
	UUID        string    `json:"uuid" yaml:"uuid"`
	Location    string    `json:"location" yaml:"location"`
	Project     string    `json:"project" yaml:"project"`
	Type        string    `json:"type" yaml:"type"`
	Count       int       `json:"count" yaml:"count"`
	FirstSeenAt time.Time `json:"first_seen_at" yaml:"first_seen_at"`
	LastSeenAt  time.Time `json:"last_seen_at" yaml:"last_seen_at"`
	LastMessage string    `json:"last_message" yaml:"last_message"`
	Severity    string    `json:"severity" yaml:"severity"`
	Status      string    `json:"status" yaml:"status"`
	EntityURL   string    `json:"entity_url" yaml:"entity_url"`
}

// WarningPut is generated from api.WarningPut - DO NOT EDIT!
type WarningPut struct {
	Status string `json:"status" yaml:"status"`
}
